/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/artisSfere.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import useScrollAnimation from './hooks/scrollAnimation'
export function ArtisSfere(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/artisSfere.glb')
  const setRef= useScrollAnimation(animations, 10)
  return (
    <group ref={setRef} {...props} dispose={null}  position={[-2,-2,0]}>
      <group name="Scene">
    <mesh name="Sphere002"receiveShadow castShadow  geometry={nodes.Sphere002.geometry} material={materials['Material.007']} scale={3.77} />
      </group>
    </group>
  )
}

useGLTF.preload('/artisSfere.glb')
