/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/Escena_total.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import useScrollAnimation from './hooks/scrollAnimation'
export function Model(props) {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Escena_total.glb')
  const { actions } = useAnimations(animations, group)
  const setRef = useScrollAnimation(animations,10)
  return (
    <group ref={setRef} {...props} dispose={null} rotation={[0,-1.6,0]} position={[0,-2,2]}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-47.55, 0.99, -4.1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[22.8, 38.05, 22.8]}>
          <group name="USDRoot" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="tracking_node_placeholder">
              <group name="PinkGkyfWkwvZoW">
                <group name="MgzlnvdhvdPmvVz">
                  <group name="jfrkeZkELiVCUCj">
                    <mesh receiveShadow castShadow  name="BDLCJBydsNjizog_0" geometry={nodes.BDLCJBydsNjizog_0.geometry} material={materials.fGwijctGaiRaYJC} />
                    <mesh receiveShadow castShadow  name="GWEiavWnRxbogtw_0" geometry={nodes.GWEiavWnRxbogtw_0.geometry} material={materials.FsunUcGyajFpQmW} />
                    <mesh receiveShadow castShadow  name="JUTNJcWwqyxbGDZ_0" geometry={nodes.JUTNJcWwqyxbGDZ_0.geometry} material={materials.LJBezuBxKRoHnAp} />
                    <mesh receiveShadow castShadow  name="PLFTnNQeqVAxicS" geometry={nodes.PLFTnNQeqVAxicS.geometry} material={materials.BLpVAsLWNICZYGG} />
                    <mesh receiveShadow castShadow  name="RFqaqXLpuCDBIGV_0" geometry={nodes.RFqaqXLpuCDBIGV_0.geometry} material={materials.nJRBoEsOhzMSqCz} />
                    <mesh receiveShadow castShadow  name="tWBbDznHihIxXam" geometry={nodes.tWBbDznHihIxXam.geometry} material={materials.OStzgRHtVBLWwiD} />
                  </group>
                  <group name="VKOyrvtwIfmqQxa">
                    <mesh receiveShadow castShadow  name="aVmapfDgqkPkjUf" geometry={nodes.aVmapfDgqkPkjUf.geometry} material={materials.WqbAhnIPgrrhfXS} />
                    <mesh receiveShadow castShadow  name="CAQeTxdpUcbxQyT" geometry={nodes.CAQeTxdpUcbxQyT.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="lgnGJJmNebyRbHq_0" geometry={nodes.lgnGJJmNebyRbHq_0.geometry} material={materials.rNCplyWedyfORFh} />
                    <mesh receiveShadow castShadow  name="qsTxqfACkdoWeLQ" geometry={nodes.qsTxqfACkdoWeLQ.geometry} material={materials.IBtgGxCVyZhjKZM} />
                    <mesh receiveShadow castShadow  name="tQCDizUpBYNcvFA" geometry={nodes.tQCDizUpBYNcvFA.geometry} material={materials.LtesZnUOMbBEAoi} />
                  </group>
                  <group name="WdanqYwxRyUXWJc">
                    <mesh receiveShadow castShadow  name="zPPSOvNamLQVyvv" geometry={nodes.zPPSOvNamLQVyvv.geometry} material={materials.qEGySvwsouNnVcn} />
                  </group>
                  <group name="xjCPRgbYHLDauvS">
                    <mesh receiveShadow castShadow  name="MoTJNOoMxqdxNvQ" geometry={nodes.MoTJNOoMxqdxNvQ.geometry} material={materials.IBtgGxCVyZhjKZM} />
                    <mesh receiveShadow castShadow  name="mZxrNiCtMrMjOMv" geometry={nodes.mZxrNiCtMrMjOMv.geometry} material={materials.WqbAhnIPgrrhfXS} />
                    <mesh receiveShadow castShadow  name="YPGjoywokSeoQFr" geometry={nodes.YPGjoywokSeoQFr.geometry} material={materials.KtvhjlxyToKjYkE} />
                  </group>
                  <mesh receiveShadow castShadow  name="aYjPeBrpBRopJbp" geometry={nodes.aYjPeBrpBRopJbp.geometry} material={materials.xHgtbqndQshkTKG} />
                  <mesh receiveShadow castShadow  name="BeQtuLXtpSTrzAH" geometry={nodes.BeQtuLXtpSTrzAH.geometry} material={materials.initialShadingGroup} />
                  <mesh receiveShadow castShadow  name="KUDomTaVduCyevu" geometry={nodes.KUDomTaVduCyevu.geometry} material={materials.KtvhjlxyToKjYkE} />
                  <mesh receiveShadow castShadow  name="QaGkMzxNzKPcqRy" geometry={nodes.QaGkMzxNzKPcqRy.geometry} material={materials.iEhZxWeNLTDdgxm} />
                  <mesh receiveShadow castShadow  name="QOfJIBEXOvXfSUh" geometry={nodes.QOfJIBEXOvXfSUh.geometry} material={materials.vsSJQngPxBJTVZb} />
                  <mesh receiveShadow castShadow  name="RUMRNTkptJGDMpy" geometry={nodes.RUMRNTkptJGDMpy.geometry} material={materials.LJBezuBxKRoHnAp} />
                </group>
                <group name="QBOwHSPSxgSiwBJ">
                  <group name="DmsxnfPLBxzvUzb">
                    <mesh receiveShadow castShadow  name="dNDonqESZOxUcei_0" geometry={nodes.dNDonqESZOxUcei_0.geometry} material={materials.LUbRMhkIhuekQRK} />
                    <mesh receiveShadow castShadow  name="IuMgFUHIyRWENxG_0" geometry={nodes.IuMgFUHIyRWENxG_0.geometry} material={materials.LcWBQfBvCzxThpp} />
                    <mesh receiveShadow castShadow  name="nJYGEbPQybRBbiN" geometry={nodes.nJYGEbPQybRBbiN.geometry} material={materials.tDZQoaroJfCIQtF} />
                    <mesh receiveShadow castShadow  name="RGbIswEcCTzqNsn_0" geometry={nodes.RGbIswEcCTzqNsn_0.geometry} material={materials.FlDKBWPodPcEeGy} />
                    <mesh receiveShadow castShadow  name="XeFHhVBtRZWPGxR" geometry={nodes.XeFHhVBtRZWPGxR.geometry} material={materials.tfbCjiZQaZkmtHx} />
                  </group>
                  <group name="hvHkgOsBqZjfnRJ">
                    <mesh receiveShadow castShadow  name="JyAbjubWrOdfygC_0" geometry={nodes.JyAbjubWrOdfygC_0.geometry} material={materials.jFPFAvCbiqflbQV} />
                    <mesh receiveShadow castShadow  name="nxFoHsySvfcSLvp" geometry={nodes.nxFoHsySvfcSLvp.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="oCklTGvTZoDWJrC_0" geometry={nodes.oCklTGvTZoDWJrC_0.geometry} material={materials.tfbCjiZQaZkmtHx} />
                  </group>
                  <group name="PBOTXpSeOPsBhmZ">
                    <mesh receiveShadow castShadow  name="BhvzCWikxrVeDTV" geometry={nodes.BhvzCWikxrVeDTV.geometry} material={materials.LtesZnUOMbBEAoi} />
                    <mesh receiveShadow castShadow  name="DLfIUIalXuQjJsL" geometry={nodes.DLfIUIalXuQjJsL.geometry} material={materials.pBMikDFQfUOsKkr} />
                    <mesh receiveShadow castShadow  name="ePYqawqlCJbCsNi" geometry={nodes.ePYqawqlCJbCsNi.geometry} material={materials.CSNzlRnZuvCyxNL} />
                    <mesh receiveShadow castShadow  name="FaUtifOQSMTXiZM" geometry={nodes.FaUtifOQSMTXiZM.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="FGDSbHbILfUmiaH" geometry={nodes.FGDSbHbILfUmiaH.geometry} material={materials.tfbCjiZQaZkmtHx} />
                    <mesh receiveShadow castShadow  name="jQXfQpudiYObSGp" geometry={nodes.jQXfQpudiYObSGp.geometry} material={materials.sWxYOtHGWTcXRMx} />
                    <mesh receiveShadow castShadow  name="KABLQLZRuEbcLWk" geometry={nodes.KABLQLZRuEbcLWk.geometry} material={materials.fdfRsQCrfvPBPfQ} />
                    <mesh receiveShadow castShadow  name="knexoFNknstHgiO" geometry={nodes.knexoFNknstHgiO.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="MMkajxMNWrwGQfi" geometry={nodes.MMkajxMNWrwGQfi.geometry} material={materials.LtesZnUOMbBEAoi} />
                    <mesh receiveShadow castShadow  name="OMkeKbwVHRBkBwM" geometry={nodes.OMkeKbwVHRBkBwM.geometry} material={materials.IkWzRHNnDaKQXIi} />
                    <mesh receiveShadow castShadow  name="qjXEDwnnBYwWcJn" geometry={nodes.qjXEDwnnBYwWcJn.geometry} material={materials.tfbCjiZQaZkmtHx} />
                    <mesh receiveShadow castShadow  name="YnrVhXEUDbStWCs" geometry={nodes.YnrVhXEUDbStWCs.geometry} material={materials.EJpkIDZfhPDUzel} />
                  </group>
                  <mesh receiveShadow castShadow  name="rJeCWUNsVVXXAbI" geometry={nodes.rJeCWUNsVVXXAbI.geometry} material={materials.psePdsxZprlxGrw} />
                  <mesh receiveShadow castShadow  name="rqSonbcVVSPWFfa_0" geometry={nodes.rqSonbcVVSPWFfa_0.geometry} material={materials.jFPFAvCbiqflbQV} />
                  <mesh receiveShadow castShadow  name="vauUojKrKkLLDtY" geometry={nodes.vauUojKrKkLLDtY.geometry} material={materials.HvAGJeQTAiWbceX} />
                  <mesh receiveShadow castShadow  name="wjSYkRykuFHJNPw" geometry={nodes.wjSYkRykuFHJNPw.geometry} material={materials.KxzouvBYEgdZhMo} />
                  <mesh receiveShadow castShadow  name="yqmgDmvGsmuPwXx_0" geometry={nodes.yqmgDmvGsmuPwXx_0.geometry} material={materials.bmOZLlCkCKhIIVe} />
                </group>
                <mesh receiveShadow castShadow  name="UCttAeyROPsgmix" geometry={nodes.UCttAeyROPsgmix.geometry} material={materials.KtvhjlxyToKjYkE} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-54.88, 0.99, -4.16]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[22.8, 38.05, 22.8]}>
          <group name="USDRoot001" position={[0, 0.19, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="tracking_node_placeholder001">
              <group name="PinkGkyfWkwvZoW001">
                <group name="CZdojDQNgDREeKv001">
                  <group name="fkgonDdxriZpnWK001">
                    <mesh receiveShadow castShadow  name="AbxQOpRbGREHXRG001" geometry={nodes.AbxQOpRbGREHXRG001.geometry} material={materials.IDdMwJVCyuFpUnA} />
                    <mesh receiveShadow castShadow  name="alSOKOYgFKIcUtR001" geometry={nodes.alSOKOYgFKIcUtR001.geometry} material={materials.sWxYOtHGWTcXRMx} />
                    <mesh receiveShadow castShadow  name="FjhETOCBEeiBmch001" geometry={nodes.FjhETOCBEeiBmch001.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="lxsKwuOPNvmzBKg_0001" geometry={nodes.lxsKwuOPNvmzBKg_0001.geometry} material={materials.KhJiSWFcsscOusf} />
                    <mesh receiveShadow castShadow  name="tWfjYtMZCfucxRt001" geometry={nodes.tWfjYtMZCfucxRt001.geometry} material={materials.fdfRsQCrfvPBPfQ} />
                  </group>
                  <mesh receiveShadow castShadow  name="rrqFqyfckTuyRuI001" geometry={nodes.rrqFqyfckTuyRuI001.geometry} material={materials.CSNzlRnZuvCyxNL} />
                  <mesh receiveShadow castShadow  name="XbtrdVaOWYmkEiU001" geometry={nodes.XbtrdVaOWYmkEiU001.geometry} material={materials.YiceMpFVTpnmoaq} />
                  <mesh receiveShadow castShadow  name="YbXWdqEcjbfTKuN_0001" geometry={nodes.YbXWdqEcjbfTKuN_0001.geometry} material={materials.GFNYbWjyDVGUwJd} />
                </group>
                <group name="MgzlnvdhvdPmvVz001">
                  <group name="jfrkeZkELiVCUCj001">
                    <mesh receiveShadow castShadow  name="BDLCJBydsNjizog_0001" geometry={nodes.BDLCJBydsNjizog_0001.geometry} material={materials.fGwijctGaiRaYJC} />
                    <mesh receiveShadow castShadow  name="GWEiavWnRxbogtw_0001" geometry={nodes.GWEiavWnRxbogtw_0001.geometry} material={materials.FsunUcGyajFpQmW} />
                    <mesh receiveShadow castShadow  name="JUTNJcWwqyxbGDZ_0001" geometry={nodes.JUTNJcWwqyxbGDZ_0001.geometry} material={materials.LJBezuBxKRoHnAp} />
                    <mesh receiveShadow castShadow  name="PLFTnNQeqVAxicS001" geometry={nodes.PLFTnNQeqVAxicS001.geometry} material={materials.BLpVAsLWNICZYGG} />
                    <mesh receiveShadow castShadow  name="RFqaqXLpuCDBIGV_0001" geometry={nodes.RFqaqXLpuCDBIGV_0001.geometry} material={materials.nJRBoEsOhzMSqCz} />
                    <mesh receiveShadow castShadow  name="tWBbDznHihIxXam001" geometry={nodes.tWBbDznHihIxXam001.geometry} material={materials.OStzgRHtVBLWwiD} />
                  </group>
                  <group name="VKOyrvtwIfmqQxa001">
                    <mesh receiveShadow castShadow  name="aVmapfDgqkPkjUf001" geometry={nodes.aVmapfDgqkPkjUf001.geometry} material={materials.WqbAhnIPgrrhfXS} />
                    <mesh receiveShadow castShadow  name="CAQeTxdpUcbxQyT001" geometry={nodes.CAQeTxdpUcbxQyT001.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="lgnGJJmNebyRbHq_0001" geometry={nodes.lgnGJJmNebyRbHq_0001.geometry} material={materials.rNCplyWedyfORFh} />
                    <mesh receiveShadow castShadow  name="qsTxqfACkdoWeLQ001" geometry={nodes.qsTxqfACkdoWeLQ001.geometry} material={materials.IBtgGxCVyZhjKZM} />
                    <mesh receiveShadow castShadow  name="tQCDizUpBYNcvFA001" geometry={nodes.tQCDizUpBYNcvFA001.geometry} material={materials.LtesZnUOMbBEAoi} />
                  </group>
                  <group name="WdanqYwxRyUXWJc001">
                    <mesh receiveShadow castShadow  name="zPPSOvNamLQVyvv001" geometry={nodes.zPPSOvNamLQVyvv001.geometry} material={materials.qEGySvwsouNnVcn} />
                  </group>
                  <group name="xjCPRgbYHLDauvS001">
                    <mesh receiveShadow castShadow  name="MoTJNOoMxqdxNvQ001" geometry={nodes.MoTJNOoMxqdxNvQ001.geometry} material={materials.IBtgGxCVyZhjKZM} />
                    <mesh receiveShadow castShadow  name="mZxrNiCtMrMjOMv001" geometry={nodes.mZxrNiCtMrMjOMv001.geometry} material={materials.WqbAhnIPgrrhfXS} />
                    <mesh receiveShadow castShadow  name="YPGjoywokSeoQFr001" geometry={nodes.YPGjoywokSeoQFr001.geometry} material={materials.KtvhjlxyToKjYkE} />
                  </group>
                  <mesh receiveShadow castShadow  name="aYjPeBrpBRopJbp001" geometry={nodes.aYjPeBrpBRopJbp001.geometry} material={materials.xHgtbqndQshkTKG} />
                  <mesh receiveShadow castShadow  name="BeQtuLXtpSTrzAH001" geometry={nodes.BeQtuLXtpSTrzAH001.geometry} material={materials.initialShadingGroup} />
                  <mesh receiveShadow castShadow  name="KUDomTaVduCyevu001" geometry={nodes.KUDomTaVduCyevu001.geometry} material={materials.KtvhjlxyToKjYkE} />
                  <mesh receiveShadow castShadow  name="QaGkMzxNzKPcqRy001" geometry={nodes.QaGkMzxNzKPcqRy001.geometry} material={materials.iEhZxWeNLTDdgxm} />
                  <mesh receiveShadow castShadow  name="QOfJIBEXOvXfSUh001" geometry={nodes.QOfJIBEXOvXfSUh001.geometry} material={materials.vsSJQngPxBJTVZb} />
                  <mesh receiveShadow castShadow  name="RUMRNTkptJGDMpy001" geometry={nodes.RUMRNTkptJGDMpy001.geometry} material={materials.LJBezuBxKRoHnAp} />
                </group>
                <group name="QBOwHSPSxgSiwBJ001">
                  <group name="DmsxnfPLBxzvUzb001">
                    <mesh receiveShadow castShadow  name="dNDonqESZOxUcei_0001" geometry={nodes.dNDonqESZOxUcei_0001.geometry} material={materials.LUbRMhkIhuekQRK} />
                    <mesh receiveShadow castShadow  name="IuMgFUHIyRWENxG_0001" geometry={nodes.IuMgFUHIyRWENxG_0001.geometry} material={materials.LcWBQfBvCzxThpp} />
                    <mesh receiveShadow castShadow  name="nJYGEbPQybRBbiN001" geometry={nodes.nJYGEbPQybRBbiN001.geometry} material={materials.tDZQoaroJfCIQtF} />
                    <mesh receiveShadow castShadow  name="RGbIswEcCTzqNsn_0001" geometry={nodes.RGbIswEcCTzqNsn_0001.geometry} material={materials.FlDKBWPodPcEeGy} />
                    <mesh receiveShadow castShadow  name="XeFHhVBtRZWPGxR001" geometry={nodes.XeFHhVBtRZWPGxR001.geometry} material={materials.tfbCjiZQaZkmtHx} />
                  </group>
                  <group name="hvHkgOsBqZjfnRJ001">
                    <mesh receiveShadow castShadow  name="JyAbjubWrOdfygC_0001" geometry={nodes.JyAbjubWrOdfygC_0001.geometry} material={materials.jFPFAvCbiqflbQV} />
                    <mesh receiveShadow castShadow  name="nxFoHsySvfcSLvp001" geometry={nodes.nxFoHsySvfcSLvp001.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="oCklTGvTZoDWJrC_0001" geometry={nodes.oCklTGvTZoDWJrC_0001.geometry} material={materials.tfbCjiZQaZkmtHx} />
                  </group>
                  <group name="PBOTXpSeOPsBhmZ001">
                    <mesh receiveShadow castShadow  name="BhvzCWikxrVeDTV001" geometry={nodes.BhvzCWikxrVeDTV001.geometry} material={materials.LtesZnUOMbBEAoi} />
                    <mesh receiveShadow castShadow  name="DLfIUIalXuQjJsL001" geometry={nodes.DLfIUIalXuQjJsL001.geometry} material={materials.pBMikDFQfUOsKkr} />
                    <mesh receiveShadow castShadow  name="ePYqawqlCJbCsNi001" geometry={nodes.ePYqawqlCJbCsNi001.geometry} material={materials.CSNzlRnZuvCyxNL} />
                    <mesh receiveShadow castShadow  name="FaUtifOQSMTXiZM001" geometry={nodes.FaUtifOQSMTXiZM001.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="FGDSbHbILfUmiaH001" geometry={nodes.FGDSbHbILfUmiaH001.geometry} material={materials.tfbCjiZQaZkmtHx} />
                    <mesh receiveShadow castShadow  name="jQXfQpudiYObSGp001" geometry={nodes.jQXfQpudiYObSGp001.geometry} material={materials.sWxYOtHGWTcXRMx} />
                    <mesh receiveShadow castShadow  name="KABLQLZRuEbcLWk001" geometry={nodes.KABLQLZRuEbcLWk001.geometry} material={materials.fdfRsQCrfvPBPfQ} />
                    <mesh receiveShadow castShadow  name="knexoFNknstHgiO001" geometry={nodes.knexoFNknstHgiO001.geometry} material={materials.KtvhjlxyToKjYkE} />
                    <mesh receiveShadow castShadow  name="MMkajxMNWrwGQfi001" geometry={nodes.MMkajxMNWrwGQfi001.geometry} material={materials.LtesZnUOMbBEAoi} />
                    <mesh receiveShadow castShadow  name="OMkeKbwVHRBkBwM001" geometry={nodes.OMkeKbwVHRBkBwM001.geometry} material={materials.IkWzRHNnDaKQXIi} />
                    <mesh receiveShadow castShadow  name="qjXEDwnnBYwWcJn001" geometry={nodes.qjXEDwnnBYwWcJn001.geometry} material={materials.tfbCjiZQaZkmtHx} />
                    <mesh receiveShadow castShadow  name="YnrVhXEUDbStWCs001" geometry={nodes.YnrVhXEUDbStWCs001.geometry} material={materials.EJpkIDZfhPDUzel} />
                  </group>
                  <mesh receiveShadow castShadow  name="rJeCWUNsVVXXAbI001" geometry={nodes.rJeCWUNsVVXXAbI001.geometry} material={materials.psePdsxZprlxGrw} />
                  <mesh receiveShadow castShadow  name="rqSonbcVVSPWFfa_0001" geometry={nodes.rqSonbcVVSPWFfa_0001.geometry} material={materials.jFPFAvCbiqflbQV} />
                  <mesh receiveShadow castShadow  name="vauUojKrKkLLDtY001" geometry={nodes.vauUojKrKkLLDtY001.geometry} material={materials.HvAGJeQTAiWbceX} />
                  <mesh receiveShadow castShadow  name="wjSYkRykuFHJNPw001" geometry={nodes.wjSYkRykuFHJNPw001.geometry} material={materials.KxzouvBYEgdZhMo} />
                  <mesh receiveShadow castShadow  name="yqmgDmvGsmuPwXx_0001" geometry={nodes.yqmgDmvGsmuPwXx_0001.geometry} material={materials.bmOZLlCkCKhIIVe} />
                </group>
                <mesh receiveShadow castShadow  name="UCttAeyROPsgmix001" geometry={nodes.UCttAeyROPsgmix001.geometry} material={materials.KtvhjlxyToKjYkE} />
              </group>
            </group>
          </group>
        </group>
        <mesh receiveShadow castShadow  name="Miss-Veedoh" geometry={nodes['Miss-Veedoh'].geometry} material={materials['Miss-veedoh']} position={[0, 1.12, 0]} rotation={[-1.5, 0, 0]} scale={0.01}>
          <mesh receiveShadow castShadow  name="Hélice" geometry={nodes.Hélice.geometry} material={materials['Miss-veedoh']} position={[-194.19, -0.17, -4.9]} rotation={[0, -0.02, -0.01]} />
          <mesh receiveShadow castShadow  name="Gouvernaille" geometry={nodes.Gouvernaille.geometry} material={materials['Miss-veedoh']} />
        </mesh >
        <mesh receiveShadow castShadow  name="Text" geometry={nodes.Text.geometry} material={materials['Material.014']} position={[-64.46, 3.67, 2.94]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={1.82} />
        <mesh receiveShadow castShadow  name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.016']} position={[-66.49, 0.84, 2.94]} rotation={[0, 1.57, 0]} scale={[1.44, 0.54, 1.18]} />
        <mesh receiveShadow castShadow  name="pilar006" geometry={nodes.pilar006.geometry} material={materials['Material.009']} position={[-67.32, 1.38, 1.04]} rotation={[0, -Math.PI / 2, 0]} scale={[0.54, 0.15, 0.54]} />
        <mesh receiveShadow castShadow  name="atap2" geometry={nodes.atap2.geometry} material={materials['Material.015']} position={[-66.49, 3.91, 4.5]} rotation={[0.45, Math.PI / 2, 0]} scale={[2.25, 0.05, 2.58]} />
        <mesh receiveShadow castShadow  name="segitiga" geometry={nodes.segitiga.geometry} material={materials['Material.009']} position={[-68.06, 2.62, 2.94]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[2.25, 0.05, 1.97]} />
        <mesh receiveShadow castShadow  name="atas_pilar" geometry={nodes.atas_pilar.geometry} material={materials['Material.009']} position={[-66.49, 2.51, 2.94]} rotation={[0, 1.57, 0]} scale={[2.25, 0.05, 1.97]} />
        <mesh receiveShadow castShadow  name="Plane002" geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-66.91, 0.54, 3.82]} rotation={[0, 1.57, 0]} scale={0.11} />
        <mesh receiveShadow castShadow  name="alas" geometry={nodes.alas.geometry} material={materials['Material.013']} position={[-66.49, 0.21, 2.94]} rotation={[0, 1.57, 0]} scale={[2.32, 0.03, 2.05]} />
        <mesh receiveShadow castShadow  name="escudo" geometry={nodes.escudo.geometry} material={materials['Material.002']} position={[-16.96, 2.46, 1.76]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[-0.03, -0.02, -0.02]} />
        <group name="medalla" position={[-36.97, 3.49, 3.11]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.9}>
          <mesh receiveShadow castShadow  name="20924_Laurel_Wreath_with_Lightning_Bolt_v2" geometry={nodes['20924_Laurel_Wreath_with_Lightning_Bolt_v2'].geometry} material={materials['20924_Laurel_Wreath_with_Lightning_Bolt_mat']} />
          <mesh receiveShadow castShadow  name="20924_Laurel_Wreath_with_Lightning_Bolt_v2_1" geometry={nodes['20924_Laurel_Wreath_with_Lightning_Bolt_v2_1'].geometry} material={materials['Material.003']} />
          <mesh receiveShadow castShadow  name="20924_Laurel_Wreath_with_Lightning_Bolt_v2_2" geometry={nodes['20924_Laurel_Wreath_with_Lightning_Bolt_v2_2'].geometry} material={materials['Material.004']} />
        </group>
        <mesh receiveShadow castShadow  name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.005']} position={[-26.26, 2.58, -2.82]} scale={[0.15, 0.31, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.005']} position={[-26.26, 2.8, -3.99]} scale={[0.15, 0.54, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.005']} position={[-26.26, 3.09, -5.15]} scale={[0.15, 0.89, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.005']} position={[-26.26, 3.46, -6.32]} scale={[0.15, 1.27, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.005']} position={[-26.26, 2.68, -3.4]} scale={[0.15, 0.43, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[-26.26, 2.93, -4.57]} scale={[0.15, 0.69, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.005']} position={[-26.26, 3.21, -5.75]} scale={[0.15, 1, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.006']} position={[-26.68, 3.07, -3.69]} scale={[0.15, 0.77, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.006']} position={[-26.68, 3.48, -4.85]} scale={[0.15, 1.26, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.006']} position={[-26.68, 3.99, -6.02]} scale={[0.15, 1.8, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.006']} position={[-26.68, 2.9, -3.1]} scale={[0.15, 0.6, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.006']} position={[-26.68, 3.24, -4.27]} scale={[0.15, 0.97, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.006']} position={[-26.68, 3.64, -5.45]} scale={[0.15, 1.42, 0.28]} />
        <mesh receiveShadow castShadow  name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.007']} position={[-26.78, 4.85, -3.97]} rotation={[0.67, 0, 0]} scale={[0.13, 0.13, 2]} />
        <group name="Cylinder001" position={[-25.88, 3.44, -6.58]} rotation={[0.05, 0.46, -1.37]} scale={[0.86, 0.11, 0.86]}>
          <mesh receiveShadow castShadow  name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Material.006']} />
          <mesh receiveShadow castShadow  name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['Material.008']} />
          <mesh receiveShadow castShadow  name="Cylinder001_3" geometry={nodes.Cylinder001_3.geometry} material={materials['Material.012']} />
          <mesh receiveShadow castShadow  name="Cylinder001_4" geometry={nodes.Cylinder001_4.geometry} material={materials['Material.011']} />
          <mesh receiveShadow castShadow  name="Cylinder001_5" geometry={nodes.Cylinder001_5.geometry} material={materials['Material.010']} />
        </group>
     </group>
    </group>
  )
}

useGLTF.preload('/Escena_total.glb')
