/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/esphere.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import useScrollAnimation from  './hooks/scrollAnimation'
export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/esphere.glb')
  const { actions } = useAnimations(animations, group)
  const setRef =useScrollAnimation(animations,10)
  return (
    <group ref={setRef} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} rotation={[0, 0.05, 0]} scale={2.57} />
      </group>
    </group>
  )
}

useGLTF.preload('/esphere.glb')
