/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/VidrioRoto.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useScrollAnimation from "./hooks/scrollAnimation";
import * as THREE from "three";
export function Model(props) {
  const myShaderMaterial = new THREE.MeshPhysicalMaterial({
    color: "rgb(250,250,250)",
    transparent: true,
    opacity: 1,
    metalness: 1,
    roughness: 0.8,
    clearcoat: 5,

    clearcoatRoughness: 5,
    transmission: 0.9,
    ior: 5, // índice de refracción del vidrio
  });

  const { nodes, materials, animations } = useGLTF("/VidrioRoto.glb");
  const useRef = useScrollAnimation(animations, 20);
  return (
    <group
      ref={useRef}
      {...props}
      dispose={null}
      rotation={[0, 11, 0]}
      position={[0, -5, 0]}
      scale={[1.8,1.8,1.8]}
    >
      <group name="Scene">
        <group name="DebugPoints" />
        <group name="Force" position={[0.01, 2.73, 0]} />

        <mesh
          name="Cube_cell"
          geometry={nodes.Cube_cell.geometry}
          material={myShaderMaterial}
          position={[0, 1.69, -2.35]}
        />
        <mesh
          name="Cube_cell001"
          geometry={nodes.Cube_cell001.geometry}
          material={myShaderMaterial}
          position={[-0.03, 4.87, -3.66]}
        />
        <mesh
          name="Cube_cell002"
          geometry={nodes.Cube_cell002.geometry}
          material={myShaderMaterial}
          position={[0, 3.02, -3.61]}
        />
        <mesh
          name="Cube_cell003"
          geometry={nodes.Cube_cell003.geometry}
          material={myShaderMaterial}
          position={[0, 3.41, 2.55]}
        />
        <mesh
          name="Cube_cell004"
          geometry={nodes.Cube_cell004.geometry}
          material={myShaderMaterial}
          position={[0, 1.3, -0.17]}
        />
        <mesh
          name="Cube_cell005"
          geometry={nodes.Cube_cell005.geometry}
          material={myShaderMaterial}
          position={[0, 1, 2.86]}
        />
        <mesh
          name="Cube_cell006"
          geometry={nodes.Cube_cell006.geometry}
          material={myShaderMaterial}
          position={[0, 0.41, -0.52]}
        />
        <mesh
          name="Cube_cell007"
          geometry={nodes.Cube_cell007.geometry}
          material={myShaderMaterial}
          position={[0, 2.83, -1.43]}
        />
        <mesh
          name="Cube_cell008"
          geometry={nodes.Cube_cell008.geometry}
          material={myShaderMaterial}
          position={[0, 1.04, 2.11]}
        />
        <mesh
          name="Cube_cell009"
          geometry={nodes.Cube_cell009.geometry}
          material={myShaderMaterial}
          position={[0, 4.12, -2.26]}
        />
        <mesh
          name="Cube_cell010"
          geometry={nodes.Cube_cell010.geometry}
          material={myShaderMaterial}
          position={[0, 0.2, -3.92]}
        />
        <mesh
          name="Cube_cell011"
          geometry={nodes.Cube_cell011.geometry}
          material={myShaderMaterial}
          position={[0, 3.03, 0.6]}
        />
        <mesh
          name="Cube_cell012"
          geometry={nodes.Cube_cell012.geometry}
          material={myShaderMaterial}
          position={[0, 3.58, -0.13]}
        />
        <mesh
          name="Cube_cell013"
          geometry={nodes.Cube_cell013.geometry}
          material={myShaderMaterial}
          position={[0.03, 0.41, 3.77]}
        />
        <mesh
          name="Cube_cell014"
          geometry={nodes.Cube_cell014.geometry}
          material={myShaderMaterial}
          position={[-0.03, 0.41, 3.77]}
        />
        <mesh
          name="Cube_cell015"
          geometry={nodes.Cube_cell015.geometry}
          material={myShaderMaterial}
          position={[0, 1.03, 0.81]}
        />
        <mesh
          name="Cube_cell016"
          geometry={nodes.Cube_cell016.geometry}
          material={myShaderMaterial}
          position={[0, 1.91, 1.74]}
        />
        <mesh
          name="Cube_cell017"
          geometry={nodes.Cube_cell017.geometry}
          material={myShaderMaterial}
          position={[0.03, 4.69, 3.58]}
        />
        <mesh
          name="Cube_cell018"
          geometry={nodes.Cube_cell018.geometry}
          material={myShaderMaterial}
          position={[0.03, 4.87, -3.66]}
        />
        <mesh
          name="Cube_cell019"
          geometry={nodes.Cube_cell019.geometry}
          material={myShaderMaterial}
          position={[0, 3.93, -0.98]}
        />
        <mesh
          name="Cube_cell020"
          geometry={nodes.Cube_cell020.geometry}
          material={myShaderMaterial}
          position={[0, 0.33, 2.27]}
        />
        <mesh
          name="Cube_cell021"
          geometry={nodes.Cube_cell021.geometry}
          material={myShaderMaterial}
          position={[0, 4.66, 2.03]}
        />
        <mesh
          name="Cube_cell022"
          geometry={nodes.Cube_cell022.geometry}
          material={myShaderMaterial}
          position={[0, 2.59, -0.12]}
        />
        <mesh
          name="Cube_cell023"
          geometry={nodes.Cube_cell023.geometry}
          material={myShaderMaterial}
          position={[0, 0.88, 1.68]}
        />
        <mesh
          name="Cube_cell024"
          geometry={nodes.Cube_cell024.geometry}
          material={myShaderMaterial}
          position={[-0.03, 4.69, 3.58]}
        />
        <mesh
          name="Cube_cell025"
          geometry={nodes.Cube_cell025.geometry}
          material={myShaderMaterial}
          position={[0, 1.17, -3.71]}
        />
        <mesh
          name="Cube_cell026"
          geometry={nodes.Cube_cell026.geometry}
          material={myShaderMaterial}
          position={[0, 2.07, 0.62]}
        />
        <mesh
          name="Cube_cell027"
          geometry={nodes.Cube_cell027.geometry}
          material={myShaderMaterial}
          position={[0, 0.28, 1.24]}
        />
        <mesh
          name="Cube_cell028"
          geometry={nodes.Cube_cell028.geometry}
          material={myShaderMaterial}
          position={[0, 4.83, 0.16]}
        />
        <mesh
          name="Cube_cell029"
          geometry={nodes.Cube_cell029.geometry}
          material={myShaderMaterial}
          position={[0, 0.32, -2.7]}
        />
        <mesh
          name="Cube_cell030"
          geometry={nodes.Cube_cell030.geometry}
          material={myShaderMaterial}
          position={[0, 2.03, -0.19]}
        />
        <mesh
          name="Cube_cell031"
          geometry={nodes.Cube_cell031.geometry}
          material={myShaderMaterial}
          position={[0, 1.35, 3.85]}
        />
        <mesh
          name="Cube_cell032"
          geometry={nodes.Cube_cell032.geometry}
          material={myShaderMaterial}
          position={[0, 2.76, 3.37]}
        />
        <mesh
          name="Cube_cell033"
          geometry={nodes.Cube_cell033.geometry}
          material={myShaderMaterial}
          position={[0, 3.24, 1.16]}
        />
        <mesh
          name="Cube_cell034"
          geometry={nodes.Cube_cell034.geometry}
          material={myShaderMaterial}
          position={[0, 1.76, -0.98]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/VidrioRoto.glb");
