/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/vidrioNuevo.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useScrollAnimation from "./hooks/scrollAnimation";
import * as THREE from "three";
export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/vidrioNuevo.glb");
  const setReft = useScrollAnimation(animations, 10);
  const Material1 = new THREE.MeshPhysicalMaterial({
    color: "rgb(250,20,250)",
    transparent: false,
    opacity: 1,
    metalness: 0,
    roughness: 0.1,
    clearcoat: 5,
    clearcoatRoughness: 5,
    transmission: 0.8,
    ior: 5, // índice de refracción del vidrio
  });
  const Material2 = new THREE.MeshPhysicalMaterial({
    color: "rgb(20,250,250)",
    transparent: false,
    opacity: 1,
    metalness: 0,
    roughness: 0.2,
    clearcoat: 5,
    clearcoatRoughness: 5,
    transmission: 0.8,
    ior: 5, // índice de refracción del vidrio
  });
  return (
    <group ref={setReft} {...props} dispose={null}rotation={[0, 4.7, 0]} scale={[1.2,1.2,1.2]}position={[0,-1,4.7]}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          position={[0, 1.04, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" scale={[1.57, 1, 1]}>
                <group name="Object_4015" />
                <group name="Object_4016" />
                <group name="Object_4017" />
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4001"
                  geometry={nodes.Object_4001.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4002"
                  geometry={nodes.Object_4002.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4003"
                  geometry={nodes.Object_4003.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4004"
                  geometry={nodes.Object_4004.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4005"
                  geometry={nodes.Object_4005.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4006"
                  geometry={nodes.Object_4006.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4007"
                  geometry={nodes.Object_4007.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4008"
                  geometry={nodes.Object_4008.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4009"
                  geometry={nodes.Object_4009.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4010"
                  geometry={nodes.Object_4010.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4011"
                  geometry={nodes.Object_4011.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4012"
                  geometry={nodes.Object_4012.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4013"
                  geometry={nodes.Object_4013.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4014"
                  geometry={nodes.Object_4014.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_4018"
                  geometry={nodes.Object_4018.geometry}
                  material={Material1}
                />
                <mesh
                  name="Object_5"
                  geometry={nodes.Object_5.geometry}
                  material={Material2}
                />
                <mesh
                  name="Object_5001"
                  geometry={nodes.Object_5001.geometry}
                  material={Material2}
                />
              </group>
            </group>
          </group>
        </group>
      
        <group name="Force" position={[0, 1, 0]} />
        <mesh
          name="Object_4_cell"
          geometry={nodes.Object_4_cell.geometry}
          material={Material1}
          position={[-0.01, 0.9, -0.1]}
        />
        <mesh
          name="Object_4_cell001"
          geometry={nodes.Object_4_cell001.geometry}
          material={Material1}
          position={[-0.01, 1.19, -0.19]}
        />
        <mesh
          name="Object_4_cell002"
          geometry={nodes.Object_4_cell002.geometry}
          material={Material1}
          position={[0, 0.51, 0.09]}
        />
        <mesh
          name="Object_4_cell003"
          geometry={nodes.Object_4_cell003.geometry}
          material={Material1}
          position={[0, 0.52, -0.61]}
        />
        <mesh
          name="Object_4_cell004"
          geometry={nodes.Object_4_cell004.geometry}
          material={Material1}
          position={[0, 0.59, -0.28]}
        />
        <mesh
          name="Object_4_cell005"
          geometry={nodes.Object_4_cell005.geometry}
          material={Material1}
          position={[0, 1.37, -0.88]}
        />
        <mesh
          name="Object_4_cell006"
          geometry={nodes.Object_4_cell006.geometry}
          material={Material1}
          position={[0, 0.75, -0.86]}
        />
        <mesh
          name="Object_4_cell007"
          geometry={nodes.Object_4_cell007.geometry}
          material={Material1}
          position={[0, 1.28, -0.47]}
        />
        <mesh
          name="Object_4_cell008"
          geometry={nodes.Object_4_cell008.geometry}
          material={Material1}
          position={[0, 0.97, -0.03]}
        />
        <mesh
          name="Object_4_cell009"
          geometry={nodes.Object_4_cell009.geometry}
          material={Material1}
          position={[0, 1.24, 0.13]}
        />
        <mesh
          name="Object_4_cell010"
          geometry={nodes.Object_4_cell010.geometry}
          material={Material1}
          position={[0, 1.17, -0.06]}
        />
        <mesh
          name="Object_4_cell011"
          geometry={nodes.Object_4_cell011.geometry}
          material={Material1}
          position={[0, 0.96, 0.08]}
        />
        <mesh
          name="Object_4_cell012"
          geometry={nodes.Object_4_cell012.geometry}
          material={Material1}
          position={[0, 1, 0]}
        />
        <mesh
          name="Object_4_cell013"
          geometry={nodes.Object_4_cell013.geometry}
          material={Material1}
          position={[0, 0.51, 0.53]}
        />
        <mesh
          name="Object_4_cell014"
          geometry={nodes.Object_4_cell014.geometry}
          material={Material1}
          position={[0, 0.88, 0.04]}
        />
        <mesh
          name="Object_4_cell015"
          geometry={nodes.Object_4_cell015.geometry}
          material={Material1}
          position={[0, 1.18, 0.37]}
        />
        <mesh
          name="Object_4_cell016"
          geometry={nodes.Object_4_cell016.geometry}
          material={Material1}
          position={[0, 1.79, 0.05]}
        />
        <mesh
          name="Object_4_cell017"
          geometry={nodes.Object_4_cell017.geometry}
          material={Material1}
          position={[0, 1.01, 0.86]}
        />
        <mesh
          name="Object_4_cell018"
          geometry={nodes.Object_4_cell018.geometry}
          material={Material1}
          position={[0, 0.86, -0.15]}
        />
        <mesh
          name="Object_4_cell019"
          geometry={nodes.Object_4_cell019.geometry}
          material={Material1}
          position={[0, 0.79, -1.01]}
        />
        <mesh
          name="Object_5_cell"
          geometry={nodes.Object_5_cell.geometry}
          material={Material2}
          position={[0, 1.17, -0.03]}
        />
        <mesh
          name="Object_5_cell001"
          geometry={nodes.Object_5_cell001.geometry}
          material={Material2}
          position={[0, 1.65, -0.62]}
        />
        <mesh
          name="Object_5_cell002"
          geometry={nodes.Object_5_cell002.geometry}
          material={Material2}
          position={[0, 0.52, 0.01]}
        />
        <mesh
          name="Object_5_cell003"
          geometry={nodes.Object_5_cell003.geometry}
          material={Material2}
          position={[0, 1.33, 0.9]}
        />
        <mesh
          name="Object_5_cell004"
          geometry={nodes.Object_5_cell004.geometry}
          material={Material2}
          position={[0, 0.75, -0.8]}
        />
        <mesh
          name="Object_5_cell005"
          geometry={nodes.Object_5_cell005.geometry}
          material={Material2}
          position={[0.01, 1.04, -0.01]}
        />
        <mesh
          name="Object_5_cell006"
          geometry={nodes.Object_5_cell006.geometry}
          material={Material2}
          position={[0, 0.95, 0.07]}
        />
        <mesh
          name="Object_5_cell007"
          geometry={nodes.Object_5_cell007.geometry}
          material={Material2}
          position={[0, 1.09, -0.18]}
        />
        <mesh
          name="Object_5_cell008"
          geometry={nodes.Object_5_cell008.geometry}
          material={Material2}
          position={[0, 1.29, -0.06]}
        />
        <mesh
          name="Object_5_cell009"
          geometry={nodes.Object_5_cell009.geometry}
          material={Material2}
          position={[0, 0.69, -0.33]}
        />
        <mesh
          name="Object_5_cell010"
          geometry={nodes.Object_5_cell010.geometry}
          material={Material2}
          position={[-0.01, 0.98, -0.04]}
        />
        <mesh
          name="Object_5_cell011"
          geometry={nodes.Object_5_cell011.geometry}
          material={Material2}
          position={[-0.01, 1.07, 0.08]}
        />
        <mesh
          name="Object_5_cell012"
          geometry={nodes.Object_5_cell012.geometry}
          material={Material2}
          position={[0.01, 1, -0.11]}
        />
        <mesh
          name="Object_5_cell013"
          geometry={nodes.Object_5_cell013.geometry}
          material={Material2}
          position={[0, 1.16, -0.42]}
        />
        <mesh
          name="Object_5_cell014"
          geometry={nodes.Object_5_cell014.geometry}
          material={Material2}
          position={[0.01, 0.88, -0.04]}
        />
        <mesh
          name="Object_5_cell015"
          geometry={nodes.Object_5_cell015.geometry}
          material={Material2}
          position={[0, 1.5, 0.45]}
        />
        <mesh
          name="Object_5_cell016"
          geometry={nodes.Object_5_cell016.geometry}
          material={Material2}
          position={[0, 1, 0.53]}
        />
        <mesh
          name="Object_5_cell017"
          geometry={nodes.Object_5_cell017.geometry}
          material={Material2}
          position={[-0.01, 1, 0.23]}
        />
        <mesh
          name="Object_5_cell018"
          geometry={nodes.Object_5_cell018.geometry}
          material={Material2}
          position={[0, 1.65, 0.05]}
        />
        <mesh
          name="Object_5_cell019"
          geometry={nodes.Object_5_cell019.geometry}
          material={Material2}
          position={[0, 0.34, 0.65]}
        />
        <mesh
          name="Object_4001_cell"
          geometry={nodes.Object_4001_cell.geometry}
          material={Material1}
          position={[-0.03, 1.28, 0.19]}
        />
        <mesh
          name="Object_4001_cell001"
          geometry={nodes.Object_4001_cell001.geometry}
          material={Material1}
          position={[-0.03, 1.29, 0.08]}
        />
        <mesh
          name="Object_4001_cell002"
          geometry={nodes.Object_4001_cell002.geometry}
          material={Material1}
          position={[-0.03, 1.9, 0.28]}
        />
        <mesh
          name="Object_4001_cell003"
          geometry={nodes.Object_4001_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.12, 0.1]}
        />
        <mesh
          name="Object_4001_cell004"
          geometry={nodes.Object_4001_cell004.geometry}
          material={Material1}
          position={[-0.03, 1.16, 0.3]}
        />
        <mesh
          name="Object_4001_cell005"
          geometry={nodes.Object_4001_cell005.geometry}
          material={Material1}
          position={[-0.03, 1.44, 0.53]}
        />
        <mesh
          name="Object_4001_cell006"
          geometry={nodes.Object_4001_cell006.geometry}
          material={Material1}
          position={[-0.03, 1.91, 0.79]}
        />
        <mesh
          name="Object_4001_cell007"
          geometry={nodes.Object_4001_cell007.geometry}
          material={Material1}
          position={[0.03, 1.28, 0.19]}
        />
        <mesh
          name="Object_4001_cell008"
          geometry={nodes.Object_4001_cell008.geometry}
          material={Material1}
          position={[0.03, 1.12, 0.1]}
        />
        <mesh
          name="Object_4001_cell009"
          geometry={nodes.Object_4001_cell009.geometry}
          material={Material1}
          position={[0.03, 1.44, 0.53]}
        />
        <mesh
          name="Object_4001_cell010"
          geometry={nodes.Object_4001_cell010.geometry}
          material={Material1}
          position={[0.03, 1.16, 0.3]}
        />
        <mesh
          name="Object_4001_cell011"
          geometry={nodes.Object_4001_cell011.geometry}
          material={Material1}
          position={[0.03, 1.91, 0.79]}
        />
        <mesh
          name="Object_4001_cell012"
          geometry={nodes.Object_4001_cell012.geometry}
          material={Material1}
          position={[0.03, 1.29, 0.08]}
        />
        <mesh
          name="Object_4001_cell013"
          geometry={nodes.Object_4001_cell013.geometry}
          material={Material1}
          position={[0.03, 1.9, 0.28]}
        />
        <mesh
          name="Object_4002_cell"
          geometry={nodes.Object_4002_cell.geometry}
          material={Material1}
          position={[0, 1.13, 0.31]}
        />
        <mesh
          name="Object_4002_cell001"
          geometry={nodes.Object_4002_cell001.geometry}
          material={Material1}
          position={[0, 1.02, 0.14]}
        />
        <mesh
          name="Object_4002_cell002"
          geometry={nodes.Object_4002_cell002.geometry}
          material={Material1}
          position={[-0.03, 1.65, 0.4]}
        />
        <mesh
          name="Object_4002_cell003"
          geometry={nodes.Object_4002_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.11, 0.09]}
        />
        <mesh
          name="Object_4002_cell004"
          geometry={nodes.Object_4002_cell004.geometry}
          material={Material1}
          position={[0.03, 1.18, 0.63]}
        />
        <mesh
          name="Object_4002_cell005"
          geometry={nodes.Object_4002_cell005.geometry}
          material={Material1}
          position={[0.03, 1.06, 0.09]}
        />
        <mesh
          name="Object_4002_cell006"
          geometry={nodes.Object_4002_cell006.geometry}
          material={Material1}
          position={[0.03, 1.26, 0.15]}
        />
        <mesh
          name="Object_4002_cell007"
          geometry={nodes.Object_4002_cell007.geometry}
          material={Material1}
          position={[0.03, 1.11, 0.09]}
        />
        <mesh
          name="Object_4002_cell008"
          geometry={nodes.Object_4002_cell008.geometry}
          material={Material1}
          position={[-0.03, 1.39, 0.93]}
        />
        <mesh
          name="Object_4002_cell009"
          geometry={nodes.Object_4002_cell009.geometry}
          material={Material1}
          position={[-0.03, 1.87, 1.01]}
        />
        <mesh
          name="Object_4002_cell010"
          geometry={nodes.Object_4002_cell010.geometry}
          material={Material1}
          position={[-0.03, 1.18, 0.63]}
        />
        <mesh
          name="Object_4002_cell011"
          geometry={nodes.Object_4002_cell011.geometry}
          material={Material1}
          position={[0.03, 1.87, 1.01]}
        />
        <mesh
          name="Object_4002_cell012"
          geometry={nodes.Object_4002_cell012.geometry}
          material={Material1}
          position={[0.03, 1.39, 0.93]}
        />
        <mesh
          name="Object_4002_cell013"
          geometry={nodes.Object_4002_cell013.geometry}
          material={Material1}
          position={[-0.03, 1.87, 0.8]}
        />
        <mesh
          name="Object_4002_cell014"
          geometry={nodes.Object_4002_cell014.geometry}
          material={Material1}
          position={[-0.03, 1.06, 0.16]}
        />
        <mesh
          name="Object_4002_cell015"
          geometry={nodes.Object_4002_cell015.geometry}
          material={Material1}
          position={[0.03, 1.87, 0.8]}
        />
        <mesh
          name="Object_4002_cell016"
          geometry={nodes.Object_4002_cell016.geometry}
          material={Material1}
          position={[0.03, 1.06, 0.16]}
        />
        <mesh
          name="Object_4002_cell017"
          geometry={nodes.Object_4002_cell017.geometry}
          material={Material1}
          position={[0.03, 1.65, 0.41]}
        />
        <mesh
          name="Object_4002_cell018"
          geometry={nodes.Object_4002_cell018.geometry}
          material={Material1}
          position={[-0.03, 1.26, 0.15]}
        />
        <mesh
          name="Object_4002_cell019"
          geometry={nodes.Object_4002_cell019.geometry}
          material={Material1}
          position={[-0.03, 1.07, 0.09]}
        />
        <mesh
          name="Object_4003_cell"
          geometry={nodes.Object_4003_cell.geometry}
          material={Material1}
          position={[-0.03, 1.33, 0.03]}
        />
        <mesh
          name="Object_4003_cell001"
          geometry={nodes.Object_4003_cell001.geometry}
          material={Material1}
          position={[-0.03, 1.05, 0.03]}
        />
        <mesh
          name="Object_4003_cell002"
          geometry={nodes.Object_4003_cell002.geometry}
          material={Material1}
          position={[-0.02, 1.02, 0.15]}
        />
        <mesh
          name="Object_4003_cell003"
          geometry={nodes.Object_4003_cell003.geometry}
          material={Material1}
          position={[0, 1.11, -0.13]}
        />
        <mesh
          name="Object_4003_cell004"
          geometry={nodes.Object_4003_cell004.geometry}
          material={Material1}
          position={[-0.03, 1.84, -0.13]}
        />
        <mesh
          name="Object_4003_cell005"
          geometry={nodes.Object_4003_cell005.geometry}
          material={Material1}
          position={[-0.03, 1.85, 0.17]}
        />
        <mesh
          name="Object_4003_cell006"
          geometry={nodes.Object_4003_cell006.geometry}
          material={Material1}
          position={[0.03, 1.84, -0.13]}
        />
        <mesh
          name="Object_4003_cell007"
          geometry={nodes.Object_4003_cell007.geometry}
          material={Material1}
          position={[0.03, 1.08, 0.02]}
        />
        <mesh
          name="Object_4003_cell008"
          geometry={nodes.Object_4003_cell008.geometry}
          material={Material1}
          position={[0.02, 1.01, -0.06]}
        />
        <mesh
          name="Object_4003_cell009"
          geometry={nodes.Object_4003_cell009.geometry}
          material={Material1}
          position={[0.03, 1.33, 0.02]}
        />
        <mesh
          name="Object_4003_cell010"
          geometry={nodes.Object_4003_cell010.geometry}
          material={Material1}
          position={[0.03, 1.85, 0.17]}
        />
        <mesh
          name="Object_4003_cell011"
          geometry={nodes.Object_4003_cell011.geometry}
          material={Material1}
          position={[0.03, 1.03, 0.15]}
        />
        <mesh
          name="Object_4004_cell"
          geometry={nodes.Object_4004_cell.geometry}
          material={Material1}
          position={[0.03, 1.36, -0.39]}
        />
        <mesh
          name="Object_4004_cell001"
          geometry={nodes.Object_4004_cell001.geometry}
          material={Material1}
          position={[-0.02, 1.03, -0.05]}
        />
        <mesh
          name="Object_4004_cell002"
          geometry={nodes.Object_4004_cell002.geometry}
          material={Material1}
          position={[0, 1.28, -0.64]}
        />
        <mesh
          name="Object_4004_cell003"
          geometry={nodes.Object_4004_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.06, -0.02]}
        />
        <mesh
          name="Object_4004_cell004"
          geometry={nodes.Object_4004_cell004.geometry}
          material={Material1}
          position={[0.03, 1.24, -0.92]}
        />
        <mesh
          name="Object_4004_cell005"
          geometry={nodes.Object_4004_cell005.geometry}
          material={Material1}
          position={[0, 1.44, -0.1]}
        />
        <mesh
          name="Object_4004_cell006"
          geometry={nodes.Object_4004_cell006.geometry}
          material={Material1}
          position={[0.03, 1.8, -0.62]}
        />
        <mesh
          name="Object_4004_cell007"
          geometry={nodes.Object_4004_cell007.geometry}
          material={Material1}
          position={[-0.03, 1.07, -0.04]}
        />
        <mesh
          name="Object_4004_cell008"
          geometry={nodes.Object_4004_cell008.geometry}
          material={Material1}
          position={[0, 1.06, -0.08]}
        />
        <mesh
          name="Object_4004_cell009"
          geometry={nodes.Object_4004_cell009.geometry}
          material={Material1}
          position={[0.02, 1.05, 0.01]}
        />
        <mesh
          name="Object_4004_cell010"
          geometry={nodes.Object_4004_cell010.geometry}
          material={Material1}
          position={[-0.03, 1.65, -0.12]}
        />
        <mesh
          name="Object_4004_cell011"
          geometry={nodes.Object_4004_cell011.geometry}
          material={Material1}
          position={[-0.03, 1.36, -0.39]}
        />
        <mesh
          name="Object_4004_cell012"
          geometry={nodes.Object_4004_cell012.geometry}
          material={Material1}
          position={[-0.02, 1.03, -0.01]}
        />
        <mesh
          name="Object_4004_cell013"
          geometry={nodes.Object_4004_cell013.geometry}
          material={Material1}
          position={[0.03, 1.06, -0.04]}
        />
        <mesh
          name="Object_4004_cell014"
          geometry={nodes.Object_4004_cell014.geometry}
          material={Material1}
          position={[0, 0.99, -0.02]}
        />
        <mesh
          name="Object_4004_cell015"
          geometry={nodes.Object_4004_cell015.geometry}
          material={Material1}
          position={[0, 1.23, 0]}
        />
        <mesh
          name="Object_4004_cell016"
          geometry={nodes.Object_4004_cell016.geometry}
          material={Material1}
          position={[-0.03, 1.24, -0.92]}
        />
        <mesh
          name="Object_4004_cell017"
          geometry={nodes.Object_4004_cell017.geometry}
          material={Material1}
          position={[0, 1.16, -0.13]}
        />
        <mesh
          name="Object_4004_cell018"
          geometry={nodes.Object_4004_cell018.geometry}
          material={Material1}
          position={[-0.03, 1.8, -0.62]}
        />
        <mesh
          name="Object_4004_cell019"
          geometry={nodes.Object_4004_cell019.geometry}
          material={Material1}
          position={[0.03, 1.65, -0.13]}
        />
        <mesh
          name="Object_4005_cell"
          geometry={nodes.Object_4005_cell.geometry}
          material={Material1}
          position={[0, 1.07, -0.1]}
        />
        <mesh
          name="Object_4005_cell001"
          geometry={nodes.Object_4005_cell001.geometry}
          material={Material1}
          position={[-0.03, 0.99, -0.28]}
        />
        <mesh
          name="Object_4005_cell002"
          geometry={nodes.Object_4005_cell002.geometry}
          material={Material1}
          position={[0, 1.08, -0.24]}
        />
        <mesh
          name="Object_4005_cell003"
          geometry={nodes.Object_4005_cell003.geometry}
          material={Material1}
          position={[0.03, 1, 0]}
        />
        <mesh
          name="Object_4005_cell004"
          geometry={nodes.Object_4005_cell004.geometry}
          material={Material1}
          position={[0.03, 1.1, -0.3]}
        />
        <mesh
          name="Object_4005_cell005"
          geometry={nodes.Object_4005_cell005.geometry}
          material={Material1}
          position={[-0.03, 0.97, -0.11]}
        />
        <mesh
          name="Object_4005_cell006"
          geometry={nodes.Object_4005_cell006.geometry}
          material={Material1}
          position={[0, 1.01, -0.34]}
        />
        <mesh
          name="Object_4005_cell007"
          geometry={nodes.Object_4005_cell007.geometry}
          material={Material1}
          position={[0, 1.02, -0.41]}
        />
        <mesh
          name="Object_4005_cell008"
          geometry={nodes.Object_4005_cell008.geometry}
          material={Material1}
          position={[-0.03, 0.99, -0.19]}
        />
        <mesh
          name="Object_4005_cell009"
          geometry={nodes.Object_4005_cell009.geometry}
          material={Material1}
          position={[0.03, 1.12, -0.36]}
        />
        <mesh
          name="Object_4005_cell010"
          geometry={nodes.Object_4005_cell010.geometry}
          material={Material1}
          position={[0, 1.12, -0.43]}
        />
        <mesh
          name="Object_4005_cell011"
          geometry={nodes.Object_4005_cell011.geometry}
          material={Material1}
          position={[-0.03, 0.97, 0.01]}
        />
        <mesh
          name="Object_4005_cell012"
          geometry={nodes.Object_4005_cell012.geometry}
          material={Material1}
          position={[0, 1.09, 0]}
        />
        <mesh
          name="Object_4005_cell013"
          geometry={nodes.Object_4005_cell013.geometry}
          material={Material1}
          position={[-0.03, 1.13, -0.36]}
        />
        <mesh
          name="Object_4005_cell014"
          geometry={nodes.Object_4005_cell014.geometry}
          material={Material1}
          position={[0.03, 0.97, -0.11]}
        />
        <mesh
          name="Object_4005_cell015"
          geometry={nodes.Object_4005_cell015.geometry}
          material={Material1}
          position={[0.03, 0.99, -0.19]}
        />
        <mesh
          name="Object_4005_cell016"
          geometry={nodes.Object_4005_cell016.geometry}
          material={Material1}
          position={[0, 0.98, -0.05]}
        />
        <mesh
          name="Object_4005_cell017"
          geometry={nodes.Object_4005_cell017.geometry}
          material={Material1}
          position={[-0.03, 1.1, -0.29]}
        />
        <mesh
          name="Object_4005_cell018"
          geometry={nodes.Object_4005_cell018.geometry}
          material={Material1}
          position={[0.03, 0.99, -0.29]}
        />
        <mesh
          name="Object_4006_cell"
          geometry={nodes.Object_4006_cell.geometry}
          material={Material1}
          position={[-0.03, 0.78, -0.39]}
        />
        <mesh
          name="Object_4006_cell001"
          geometry={nodes.Object_4006_cell001.geometry}
          material={Material1}
          position={[-0.03, 0.87, -0.4]}
        />
        <mesh
          name="Object_4006_cell002"
          geometry={nodes.Object_4006_cell002.geometry}
          material={Material1}
          position={[-0.03, 0.84, -0.45]}
        />
        <mesh
          name="Object_4006_cell003"
          geometry={nodes.Object_4006_cell003.geometry}
          material={Material1}
          position={[-0.03, 0.79, -0.33]}
        />
        <mesh
          name="Object_4006_cell004"
          geometry={nodes.Object_4006_cell004.geometry}
          material={Material1}
          position={[-0.03, 0.8, -0.26]}
        />
        <mesh
          name="Object_4006_cell005"
          geometry={nodes.Object_4006_cell005.geometry}
          material={Material1}
          position={[-0.03, 0.88, -0.33]}
        />
        <mesh
          name="Object_4006_cell006"
          geometry={nodes.Object_4006_cell006.geometry}
          material={Material1}
          position={[-0.03, 0.88, -0.25]}
        />
        <mesh
          name="Object_4006_cell007"
          geometry={nodes.Object_4006_cell007.geometry}
          material={Material1}
          position={[0.03, 0.87, -0.4]}
        />
        <mesh
          name="Object_4006_cell008"
          geometry={nodes.Object_4006_cell008.geometry}
          material={Material1}
          position={[0.03, 0.78, -0.39]}
        />
        <mesh
          name="Object_4006_cell009"
          geometry={nodes.Object_4006_cell009.geometry}
          material={Material1}
          position={[0.03, 0.84, -0.45]}
        />
        <mesh
          name="Object_4006_cell010"
          geometry={nodes.Object_4006_cell010.geometry}
          material={Material1}
          position={[0.03, 0.79, -0.33]}
        />
        <mesh
          name="Object_4006_cell011"
          geometry={nodes.Object_4006_cell011.geometry}
          material={Material1}
          position={[0.03, 0.8, -0.26]}
        />
        <mesh
          name="Object_4006_cell012"
          geometry={nodes.Object_4006_cell012.geometry}
          material={Material1}
          position={[0.03, 0.88, -0.33]}
        />
        <mesh
          name="Object_4006_cell013"
          geometry={nodes.Object_4006_cell013.geometry}
          material={Material1}
          position={[0.03, 0.88, -0.25]}
        />
        <mesh
          name="Object_4007_cell"
          geometry={nodes.Object_4007_cell.geometry}
          material={Material1}
          position={[0, 1.01, -0.42]}
        />
        <mesh
          name="Object_4007_cell001"
          geometry={nodes.Object_4007_cell001.geometry}
          material={Material1}
          position={[0, 0.87, -0.4]}
        />
        <mesh
          name="Object_4007_cell002"
          geometry={nodes.Object_4007_cell002.geometry}
          material={Material1}
          position={[0, 0.87, -0.08]}
        />
        <mesh
          name="Object_4007_cell003"
          geometry={nodes.Object_4007_cell003.geometry}
          material={Material1}
          position={[-0.01, 0.86, -0.84]}
        />
        <mesh
          name="Object_4007_cell004"
          geometry={nodes.Object_4007_cell004.geometry}
          material={Material1}
          position={[-0.03, 0.87, -0.49]}
        />
        <mesh
          name="Object_4007_cell005"
          geometry={nodes.Object_4007_cell005.geometry}
          material={Material1}
          position={[0, 0.8, -0.43]}
        />
        <mesh
          name="Object_4007_cell006"
          geometry={nodes.Object_4007_cell006.geometry}
          material={Material1}
          position={[0, 1.07, -0.09]}
        />
        <mesh
          name="Object_4007_cell007"
          geometry={nodes.Object_4007_cell007.geometry}
          material={Material1}
          position={[-0.03, 1.02, -0.92]}
        />
        <mesh
          name="Object_4007_cell008"
          geometry={nodes.Object_4007_cell008.geometry}
          material={Material1}
          position={[0, 1.02, -0.28]}
        />
        <mesh
          name="Object_4007_cell009"
          geometry={nodes.Object_4007_cell009.geometry}
          material={Material1}
          position={[0.03, 1.08, -0.54]}
        />
        <mesh
          name="Object_4007_cell010"
          geometry={nodes.Object_4007_cell010.geometry}
          material={Material1}
          position={[0.03, 0.86, -0.48]}
        />
        <mesh
          name="Object_4007_cell011"
          geometry={nodes.Object_4007_cell011.geometry}
          material={Material1}
          position={[0, 1.07, -0.71]}
        />
        <mesh
          name="Object_4007_cell012"
          geometry={nodes.Object_4007_cell012.geometry}
          material={Material1}
          position={[-0.01, 1.02, -0.18]}
        />
        <mesh
          name="Object_4007_cell013"
          geometry={nodes.Object_4007_cell013.geometry}
          material={Material1}
          position={[0, 0.86, -0.33]}
        />
        <mesh
          name="Object_4007_cell014"
          geometry={nodes.Object_4007_cell014.geometry}
          material={Material1}
          position={[-0.01, 0.97, -0.07]}
        />
        <mesh
          name="Object_4007_cell015"
          geometry={nodes.Object_4007_cell015.geometry}
          material={Material1}
          position={[-0.03, 1.06, -0.53]}
        />
        <mesh
          name="Object_4007_cell016"
          geometry={nodes.Object_4007_cell016.geometry}
          material={Material1}
          position={[0, 0.86, -0.23]}
        />
        <mesh
          name="Object_4007_cell017"
          geometry={nodes.Object_4007_cell017.geometry}
          material={Material1}
          position={[0.03, 1.02, -0.92]}
        />
        <mesh
          name="Object_4007_cell018"
          geometry={nodes.Object_4007_cell018.geometry}
          material={Material1}
          position={[0, 0.84, -0.14]}
        />
        <mesh
          name="Object_4007_cell019"
          geometry={nodes.Object_4007_cell019.geometry}
          material={Material1}
          position={[0, 0.91, -0.58]}
        />
        <mesh
          name="Object_4008_cell"
          geometry={nodes.Object_4008_cell.geometry}
          material={Material1}
          position={[0, 0.9, 0.41]}
        />
        <mesh
          name="Object_4008_cell001"
          geometry={nodes.Object_4008_cell001.geometry}
          material={Material1}
          position={[0, 0.86, 0.26]}
        />
        <mesh
          name="Object_4008_cell002"
          geometry={nodes.Object_4008_cell002.geometry}
          material={Material1}
          position={[-0.03, 1.01, 0.12]}
        />
        <mesh
          name="Object_4008_cell003"
          geometry={nodes.Object_4008_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.11, 0.32]}
        />
        <mesh
          name="Object_4008_cell004"
          geometry={nodes.Object_4008_cell004.geometry}
          material={Material1}
          position={[-0.03, 1.14, 0.11]}
        />
        <mesh
          name="Object_4008_cell005"
          geometry={nodes.Object_4008_cell005.geometry}
          material={Material1}
          position={[0, 0.9, 0.79]}
        />
        <mesh
          name="Object_4008_cell006"
          geometry={nodes.Object_4008_cell006.geometry}
          material={Material1}
          position={[0.03, 1.13, 0.94]}
        />
        <mesh
          name="Object_4008_cell007"
          geometry={nodes.Object_4008_cell007.geometry}
          material={Material1}
          position={[0.03, 1.11, 0.32]}
        />
        <mesh
          name="Object_4008_cell008"
          geometry={nodes.Object_4008_cell008.geometry}
          material={Material1}
          position={[0.03, 0.84, 0.07]}
        />
        <mesh
          name="Object_4008_cell009"
          geometry={nodes.Object_4008_cell009.geometry}
          material={Material1}
          position={[-0.03, 0.84, 0.07]}
        />
        <mesh
          name="Object_4008_cell010"
          geometry={nodes.Object_4008_cell010.geometry}
          material={Material1}
          position={[-0.03, 1.14, 0.63]}
        />
        <mesh
          name="Object_4008_cell011"
          geometry={nodes.Object_4008_cell011.geometry}
          material={Material1}
          position={[0, 0.88, 0.53]}
        />
        <mesh
          name="Object_4008_cell012"
          geometry={nodes.Object_4008_cell012.geometry}
          material={Material1}
          position={[0, 0.88, 0.35]}
        />
        <mesh
          name="Object_4008_cell013"
          geometry={nodes.Object_4008_cell013.geometry}
          material={Material1}
          position={[0.03, 1.14, 0.11]}
        />
        <mesh
          name="Object_4008_cell014"
          geometry={nodes.Object_4008_cell014.geometry}
          material={Material1}
          position={[0.03, 1.14, 0.63]}
        />
        <mesh
          name="Object_4008_cell015"
          geometry={nodes.Object_4008_cell015.geometry}
          material={Material1}
          position={[0, 0.87, 0.99]}
        />
        <mesh
          name="Object_4008_cell016"
          geometry={nodes.Object_4008_cell016.geometry}
          material={Material1}
          position={[-0.03, 0.9, 0.17]}
        />
        <mesh
          name="Object_4008_cell017"
          geometry={nodes.Object_4008_cell017.geometry}
          material={Material1}
          position={[0.03, 1.01, 0.12]}
        />
        <mesh
          name="Object_4008_cell018"
          geometry={nodes.Object_4008_cell018.geometry}
          material={Material1}
          position={[-0.03, 1.13, 0.94]}
        />
        <mesh
          name="Object_4008_cell019"
          geometry={nodes.Object_4008_cell019.geometry}
          material={Material1}
          position={[0.03, 0.9, 0.17]}
        />
        <mesh
          name="Object_4009_cell"
          geometry={nodes.Object_4009_cell.geometry}
          material={Material1}
          position={[-0.03, 0.95, 0.2]}
        />
        <mesh
          name="Object_4009_cell001"
          geometry={nodes.Object_4009_cell001.geometry}
          material={Material1}
          position={[-0.03, 0.87, 0.23]}
        />
        <mesh
          name="Object_4009_cell002"
          geometry={nodes.Object_4009_cell002.geometry}
          material={Material1}
          position={[-0.03, 0.9, 0.27]}
        />
        <mesh
          name="Object_4009_cell003"
          geometry={nodes.Object_4009_cell003.geometry}
          material={Material1}
          position={[-0.03, 0.96, 0.27]}
        />
        <mesh
          name="Object_4009_cell004"
          geometry={nodes.Object_4009_cell004.geometry}
          material={Material1}
          position={[0.03, 0.87, 0.23]}
        />
        <mesh
          name="Object_4009_cell005"
          geometry={nodes.Object_4009_cell005.geometry}
          material={Material1}
          position={[0.03, 0.95, 0.2]}
        />
        <mesh
          name="Object_4009_cell006"
          geometry={nodes.Object_4009_cell006.geometry}
          material={Material1}
          position={[0.03, 0.96, 0.27]}
        />
        <mesh
          name="Object_4009_cell007"
          geometry={nodes.Object_4009_cell007.geometry}
          material={Material1}
          position={[0.03, 0.9, 0.27]}
        />
        <mesh
          name="Object_4010_cell"
          geometry={nodes.Object_4010_cell.geometry}
          material={Material1}
          position={[0.03, 1, -0.13]}
        />
        <mesh
          name="Object_4010_cell001"
          geometry={nodes.Object_4010_cell001.geometry}
          material={Material1}
          position={[-0.02, 1.03, 0.04]}
        />
        <mesh
          name="Object_4010_cell002"
          geometry={nodes.Object_4010_cell002.geometry}
          material={Material1}
          position={[0.02, 0.96, 0.04]}
        />
        <mesh
          name="Object_4010_cell003"
          geometry={nodes.Object_4010_cell003.geometry}
          material={Material1}
          position={[-0.03, 0.98, -0.01]}
        />
        <mesh
          name="Object_4010_cell004"
          geometry={nodes.Object_4010_cell004.geometry}
          material={Material1}
          position={[-0.03, 0.85, -0.1]}
        />
        <mesh
          name="Object_4010_cell005"
          geometry={nodes.Object_4010_cell005.geometry}
          material={Material1}
          position={[0, 0.91, -0.01]}
        />
        <mesh
          name="Object_4010_cell006"
          geometry={nodes.Object_4010_cell006.geometry}
          material={Material1}
          position={[0.02, 1.03, 0]}
        />
        <mesh
          name="Object_4010_cell007"
          geometry={nodes.Object_4010_cell007.geometry}
          material={Material1}
          position={[0.03, 1.01, 0.04]}
        />
        <mesh
          name="Object_4010_cell008"
          geometry={nodes.Object_4010_cell008.geometry}
          material={Material1}
          position={[-0.03, 0.99, -0.12]}
        />
        <mesh
          name="Object_4010_cell009"
          geometry={nodes.Object_4010_cell009.geometry}
          material={Material1}
          position={[-0.03, 1.02, -0.01]}
        />
        <mesh
          name="Object_4010_cell010"
          geometry={nodes.Object_4010_cell010.geometry}
          material={Material1}
          position={[0.03, 0.92, -0.15]}
        />
        <mesh
          name="Object_4010_cell011"
          geometry={nodes.Object_4010_cell011.geometry}
          material={Material1}
          position={[0.03, 0.97, -0.01]}
        />
        <mesh
          name="Object_4010_cell012"
          geometry={nodes.Object_4010_cell012.geometry}
          material={Material1}
          position={[-0.02, 1, 0.05]}
        />
        <mesh
          name="Object_4010_cell013"
          geometry={nodes.Object_4010_cell013.geometry}
          material={Material1}
          position={[-0.01, 0.91, -0.08]}
        />
        <mesh
          name="Object_4010_cell014"
          geometry={nodes.Object_4010_cell014.geometry}
          material={Material1}
          position={[0.03, 0.85, -0.1]}
        />
        <mesh
          name="Object_4010_cell015"
          geometry={nodes.Object_4010_cell015.geometry}
          material={Material1}
          position={[0.01, 0.99, -0.05]}
        />
        <mesh
          name="Object_4010_cell016"
          geometry={nodes.Object_4010_cell016.geometry}
          material={Material1}
          position={[0.03, 1.01, 0.01]}
        />
        <mesh
          name="Object_4010_cell017"
          geometry={nodes.Object_4010_cell017.geometry}
          material={Material1}
          position={[-0.03, 0.92, -0.15]}
        />
        <mesh
          name="Object_4010_cell018"
          geometry={nodes.Object_4010_cell018.geometry}
          material={Material1}
          position={[0.03, 0.93, -0.09]}
        />
        <mesh
          name="Object_4010_cell019"
          geometry={nodes.Object_4010_cell019.geometry}
          material={Material1}
          position={[-0.03, 0.96, 0.02]}
        />
        <mesh
          name="Object_4011_cell"
          geometry={nodes.Object_4011_cell.geometry}
          material={Material1}
          position={[-0.03, 0.84, 0.37]}
        />
        <mesh
          name="Object_4011_cell001"
          geometry={nodes.Object_4011_cell001.geometry}
          material={Material1}
          position={[0.02, 0.75, 0.22]}
        />
        <mesh
          name="Object_4011_cell002"
          geometry={nodes.Object_4011_cell002.geometry}
          material={Material1}
          position={[0.01, 0.73, 0.36]}
        />
        <mesh
          name="Object_4011_cell003"
          geometry={nodes.Object_4011_cell003.geometry}
          material={Material1}
          position={[-0.03, 0.78, 0.34]}
        />
        <mesh
          name="Object_4011_cell004"
          geometry={nodes.Object_4011_cell004.geometry}
          material={Material1}
          position={[0, 0.84, 0.27]}
        />
        <mesh
          name="Object_4011_cell005"
          geometry={nodes.Object_4011_cell005.geometry}
          material={Material1}
          position={[0.03, 0.79, 0.2]}
        />
        <mesh
          name="Object_4011_cell006"
          geometry={nodes.Object_4011_cell006.geometry}
          material={Material1}
          position={[-0.03, 0.74, 0.29]}
        />
        <mesh
          name="Object_4011_cell007"
          geometry={nodes.Object_4011_cell007.geometry}
          material={Material1}
          position={[-0.03, 0.73, 0.21]}
        />
        <mesh
          name="Object_4011_cell008"
          geometry={nodes.Object_4011_cell008.geometry}
          material={Material1}
          position={[-0.03, 0.77, 0.2]}
        />
        <mesh
          name="Object_4011_cell009"
          geometry={nodes.Object_4011_cell009.geometry}
          material={Material1}
          position={[0, 0.88, 0.21]}
        />
        <mesh
          name="Object_4011_cell010"
          geometry={nodes.Object_4011_cell010.geometry}
          material={Material1}
          position={[-0.03, 0.83, 0.38]}
        />
        <mesh
          name="Object_4011_cell011"
          geometry={nodes.Object_4011_cell011.geometry}
          material={Material1}
          position={[0, 0.85, 0.2]}
        />
        <mesh
          name="Object_4011_cell012"
          geometry={nodes.Object_4011_cell012.geometry}
          material={Material1}
          position={[-0.01, 0.77, 0.35]}
        />
        <mesh
          name="Object_4011_cell013"
          geometry={nodes.Object_4011_cell013.geometry}
          material={Material1}
          position={[0.02, 0.73, 0.29]}
        />
        <mesh
          name="Object_4011_cell014"
          geometry={nodes.Object_4011_cell014.geometry}
          material={Material1}
          position={[-0.02, 0.79, 0.23]}
        />
        <mesh
          name="Object_4011_cell015"
          geometry={nodes.Object_4011_cell015.geometry}
          material={Material1}
          position={[0, 0.83, 0.32]}
        />
        <mesh
          name="Object_4011_cell016"
          geometry={nodes.Object_4011_cell016.geometry}
          material={Material1}
          position={[-0.03, 0.83, 0.35]}
        />
        <mesh
          name="Object_4011_cell017"
          geometry={nodes.Object_4011_cell017.geometry}
          material={Material1}
          position={[0.02, 0.8, 0.35]}
        />
        <mesh
          name="Object_4011_cell018"
          geometry={nodes.Object_4011_cell018.geometry}
          material={Material1}
          position={[0.01, 0.83, 0.2]}
        />
        <mesh
          name="Object_4012_cell"
          geometry={nodes.Object_4012_cell.geometry}
          material={Material1}
          position={[-0.03, 0.9, 0.22]}
        />
        <mesh
          name="Object_4012_cell001"
          geometry={nodes.Object_4012_cell001.geometry}
          material={Material1}
          position={[-0.03, 0.93, 0.26]}
        />
        <mesh
          name="Object_4012_cell002"
          geometry={nodes.Object_4012_cell002.geometry}
          material={Material1}
          position={[-0.03, 0.83, 0.21]}
        />
        <mesh
          name="Object_4012_cell003"
          geometry={nodes.Object_4012_cell003.geometry}
          material={Material1}
          position={[-0.03, 0.84, 0.28]}
        />
        <mesh
          name="Object_4012_cell004"
          geometry={nodes.Object_4012_cell004.geometry}
          material={Material1}
          position={[0.03, 0.9, 0.22]}
        />
        <mesh
          name="Object_4012_cell005"
          geometry={nodes.Object_4012_cell005.geometry}
          material={Material1}
          position={[0.03, 0.93, 0.26]}
        />
        <mesh
          name="Object_4012_cell006"
          geometry={nodes.Object_4012_cell006.geometry}
          material={Material1}
          position={[0.03, 0.84, 0.28]}
        />
        <mesh
          name="Object_4012_cell007"
          geometry={nodes.Object_4012_cell007.geometry}
          material={Material1}
          position={[0.03, 0.83, 0.21]}
        />
        <mesh
          name="Object_4013_cell"
          geometry={nodes.Object_4013_cell.geometry}
          material={Material1}
          position={[0.03, 0.99, -0.01]}
        />
        <mesh
          name="Object_4013_cell001"
          geometry={nodes.Object_4013_cell001.geometry}
          material={Material1}
          position={[0.03, 0.93, 0.04]}
        />
        <mesh
          name="Object_4013_cell002"
          geometry={nodes.Object_4013_cell002.geometry}
          material={Material1}
          position={[0.03, 0.93, -0.02]}
        />
        <mesh
          name="Object_4013_cell003"
          geometry={nodes.Object_4013_cell003.geometry}
          material={Material1}
          position={[0.03, 0.97, 0.06]}
        />
        <mesh
          name="Object_4013_cell004"
          geometry={nodes.Object_4013_cell004.geometry}
          material={Material1}
          position={[0.03, 0.97, 0.02]}
        />
        <mesh
          name="Object_4013_cell005"
          geometry={nodes.Object_4013_cell005.geometry}
          material={Material1}
          position={[0.03, 0.97, 0.03]}
        />
        <mesh
          name="Object_4013_cell006"
          geometry={nodes.Object_4013_cell006.geometry}
          material={Material1}
          position={[0.02, 1, 0.06]}
        />
        <mesh
          name="Object_4013_cell007"
          geometry={nodes.Object_4013_cell007.geometry}
          material={Material1}
          position={[0.03, 1, 0.03]}
        />
        <mesh
          name="Object_4013_cell008"
          geometry={nodes.Object_4013_cell008.geometry}
          material={Material1}
          position={[-0.03, 0.93, -0.02]}
        />
        <mesh
          name="Object_4013_cell009"
          geometry={nodes.Object_4013_cell009.geometry}
          material={Material1}
          position={[-0.03, 0.99, -0.01]}
        />
        <mesh
          name="Object_4013_cell010"
          geometry={nodes.Object_4013_cell010.geometry}
          material={Material1}
          position={[-0.03, 0.93, 0.04]}
        />
        <mesh
          name="Object_4013_cell011"
          geometry={nodes.Object_4013_cell011.geometry}
          material={Material1}
          position={[-0.02, 0.98, 0.07]}
        />
        <mesh
          name="Object_4013_cell012"
          geometry={nodes.Object_4013_cell012.geometry}
          material={Material1}
          position={[-0.03, 0.98, 0.02]}
        />
        <mesh
          name="Object_4013_cell013"
          geometry={nodes.Object_4013_cell013.geometry}
          material={Material1}
          position={[-0.03, 0.97, 0.06]}
        />
        <mesh
          name="Object_4013_cell014"
          geometry={nodes.Object_4013_cell014.geometry}
          material={Material1}
          position={[-0.02, 0.97, 0.03]}
        />
        <mesh
          name="Object_4013_cell015"
          geometry={nodes.Object_4013_cell015.geometry}
          material={Material1}
          position={[-0.03, 0.96, 0.02]}
        />
        <mesh
          name="Object_4013_cell016"
          geometry={nodes.Object_4013_cell016.geometry}
          material={Material1}
          position={[-0.03, 1, 0.06]}
        />
        <mesh
          name="Object_4013_cell017"
          geometry={nodes.Object_4013_cell017.geometry}
          material={Material1}
          position={[-0.03, 1, 0.03]}
        />
        <mesh
          name="Object_4014_cell"
          geometry={nodes.Object_4014_cell.geometry}
          material={Material1}
          position={[-0.03, 1.43, 0.33]}
        />
        <mesh
          name="Object_4014_cell001"
          geometry={nodes.Object_4014_cell001.geometry}
          material={Material1}
          position={[-0.03, 1.3, 0.2]}
        />
        <mesh
          name="Object_4014_cell002"
          geometry={nodes.Object_4014_cell002.geometry}
          material={Material1}
          position={[-0.03, 1.17, 0.37]}
        />
        <mesh
          name="Object_4014_cell003"
          geometry={nodes.Object_4014_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.37, 0.08]}
        />
        <mesh
          name="Object_4014_cell004"
          geometry={nodes.Object_4014_cell004.geometry}
          material={Material1}
          position={[0.03, 1.17, 0.37]}
        />
        <mesh
          name="Object_4014_cell005"
          geometry={nodes.Object_4014_cell005.geometry}
          material={Material1}
          position={[0.03, 1.43, 0.33]}
        />
        <mesh
          name="Object_4014_cell006"
          geometry={nodes.Object_4014_cell006.geometry}
          material={Material1}
          position={[0.03, 1.37, 0.08]}
        />
        <mesh
          name="Object_4014_cell007"
          geometry={nodes.Object_4014_cell007.geometry}
          material={Material1}
          position={[0.03, 1.3, 0.2]}
        />
        <mesh
          name="Object_5001_cell"
          geometry={nodes.Object_5001_cell.geometry}
          material={Material2}
          position={[-0.03, 1.08, -0.1]}
        />
        <mesh
          name="Object_5001_cell001"
          geometry={nodes.Object_5001_cell001.geometry}
          material={Material2}
          position={[-0.03, 1.84, -0.11]}
        />
        <mesh
          name="Object_5001_cell002"
          geometry={nodes.Object_5001_cell002.geometry}
          material={Material2}
          position={[0.03, 1.84, -0.13]}
        />
        <mesh
          name="Object_5001_cell003"
          geometry={nodes.Object_5001_cell003.geometry}
          material={Material2}
          position={[0.03, 1.08, -0.1]}
        />
        <mesh
          name="Object_5001_cell004"
          geometry={nodes.Object_5001_cell004.geometry}
          material={Material2}
          position={[0.03, 1.09, 0.02]}
        />
        <mesh
          name="Object_5001_cell005"
          geometry={nodes.Object_5001_cell005.geometry}
          material={Material2}
          position={[-0.03, 1.09, 0.02]}
        />
        <mesh
          name="Object_5001_cell007"
          geometry={nodes.Object_5001_cell007.geometry}
          material={Material2}
          position={[0.03, 1.33, 0.02]}
        />
        <mesh
          name="Object_5001_cell009"
          geometry={nodes.Object_5001_cell009.geometry}
          material={Material2}
          position={[-0.03, 1.03, 0.15]}
        />
        <mesh
          name="Object_5001_cell010"
          geometry={nodes.Object_5001_cell010.geometry}
          material={Material2}
          position={[0.03, 1.85, 0.17]}
        />
        <mesh
          name="Object_5001_cell011"
          geometry={nodes.Object_5001_cell011.geometry}
          material={Material2}
          position={[-0.03, 1.85, 0.17]}
        />
        <mesh
          name="Object_5001_cell012"
          geometry={nodes.Object_5001_cell012.geometry}
          material={Material2}
          position={[-0.02, 1.79, -0.26]}
        />
        <mesh
          name="Object_5001_cell013"
          geometry={nodes.Object_5001_cell013.geometry}
          material={Material2}
          position={[-0.01, 1.85, 0.17]}
        />
        <mesh
          name="Object_5001_cell014"
          geometry={nodes.Object_5001_cell014.geometry}
          material={Material2}
          position={[0, 1.79, -0.16]}
        />
        <mesh
          name="Object_5001_cell015"
          geometry={nodes.Object_5001_cell015.geometry}
          material={Material2}
          position={[-0.01, 1.84, -0.1]}
        />
        <mesh
          name="Object_5001_cell016"
          geometry={nodes.Object_5001_cell016.geometry}
          material={Material2}
          position={[0, 1.83, -0.17]}
        />
        <mesh
          name="Object_5001_cell017"
          geometry={nodes.Object_5001_cell017.geometry}
          material={Material2}
          position={[0, 1.85, 0.17]}
        />
        <mesh
          name="Object_4015_cell"
          geometry={nodes.Object_4015_cell.geometry}
          material={Material1}
          position={[-0.03, 2.04, 0.27]}
        />
        <mesh
          name="Object_4015_cell001"
          geometry={nodes.Object_4015_cell001.geometry}
          material={Material1}
          position={[0.03, 2.04, 0.27]}
        />
        <mesh
          name="Object_4018_cell"
          geometry={nodes.Object_4018_cell.geometry}
          material={Material1}
          position={[-0.03, 1.06, 0.03]}
        />
        <mesh
          name="Object_4018_cell001"
          geometry={nodes.Object_4018_cell001.geometry}
          material={Material1}
          position={[-0.03, 1.04, 0.06]}
        />
        <mesh
          name="Object_4018_cell002"
          geometry={nodes.Object_4018_cell002.geometry}
          material={Material1}
          position={[-0.01, 1.07, -0.01]}
        />
        <mesh
          name="Object_4018_cell003"
          geometry={nodes.Object_4018_cell003.geometry}
          material={Material1}
          position={[-0.03, 1.01, 0]}
        />
        <mesh
          name="Object_4018_cell004"
          geometry={nodes.Object_4018_cell004.geometry}
          material={Material1}
          position={[0.02, 1.07, 0.03]}
        />
        <mesh
          name="Object_4018_cell005"
          geometry={nodes.Object_4018_cell005.geometry}
          material={Material1}
          position={[0.03, 1.02, 0]}
        />
        <mesh
          name="Object_4018_cell006"
          geometry={nodes.Object_4018_cell006.geometry}
          material={Material1}
          position={[0.03, 1.04, 0.06]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/vidrioNuevo.glb");
