/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/vidrioSimple.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelS(props) {
  const { nodes, materials } = useGLTF('/vidrioSimple.glb')
  return (
    <group {...props} dispose={null} rotation={[0, 4.7, 0]} position={[0,0,4.5]}>
      <group scale={[1.57, 1, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/vidrioSimple.glb')
