/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/windowNoBroken.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelNoBroken(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/windowNoBroken.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={[3, 3, 3]} position={[2,0,-3]}ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0, 1]} rotation={[-Math.PI, 0, 0]} scale={[-0.1, -1, -2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/windowNoBroken.glb')
