/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../public/window.glb
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";
import { useScroll } from "framer-motion";

export function Model(props) {
  const [windowHeight, setWindowHeight] = useState(window.innerHeight);
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/windows.glb");
  // const { actions } = useAnimations(animations, group);
  const [state, setState] = useState({
    animationDirection: 1,
    lastScrollPosition: 0,
  });
  // const [animationPaused, setAnimationPaused] = useState(false);
  // const [actionsArr, setActionsArr] = useState([]);
  // let scrollTimeout;

  const [scroll, setScroll] = useState();
  useEffect(() => {
    function handleScroll() {
      setScroll(window.scrollY);
    }
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const FPS = 30;

  // const { mixer } = useAnimations(animations, group);

  // const clock = new THREE.Clock();

  const [currentTime, setCurrentTime] = useState(0);

  useEffect(() => {
    let percentScroll = (scroll * 100) / windowHeight;

    console.log({ state: state.animationDirection });
    if (animations.length > 0) {
      const mixer = new THREE.AnimationMixer(group.current);
      animations.forEach((animation) => {
        const action = mixer.clipAction(animation);
        let frameDuration = 1 / FPS; // duración de un solo fotograma en segundos
        let totalFrames = animation.duration * FPS;
        animation.loop = false;

        // let totalFrames = animations.duration * FPS; // número total de fotogramas en la animació)
        if (state.animationDirection < 0) {
          action.paused = true;
          mixer.setTime(currentTime);
          action.paused = false;
          mixer.timeScale = -1;
          action.play();
        } else {
          action.play();
          setCurrentTime(currentTime + 1);
          mixer.setTime(currentTime * frameDuration);
        }

        // número de fotogramas por segundo
      });
    }
  }, [scroll]);

  const [prevScrollY, setPrevScrollY] = useState(0);
  const [scrollDirection, setScrollDirection] = useState("");

  useEffect(() => {
    const currentScrollY = scroll;
    if (currentScrollY > prevScrollY) {
      setScrollDirection(1);
      setState({ ...state, animationDirection: 1 });
    } else if (currentScrollY < prevScrollY) {
      setScrollDirection(-1);
      setState({ ...state, animationDirection: -1 });
    }
    setPrevScrollY(currentScrollY);
  }, [scroll]);
  return (
    <>
      <group
        scale={[3, 3, 3]}
        position={[2, 0, -3]}
        ref={group}
        {...props}
        dispose={null}
      >
        <group name="Scene">
          <group name="Cube_cell028" position={[0.06, -0.38, 1]} />
          <group name="Force" position={[0, -0.36, 0]} />
          <group name="Cube_cell094" position={[0.06, -0.38, 3]} />
          <group name="Force001" position={[0, -0.36, 2]} />
          <mesh
            name="Cube_cell"
            geometry={nodes.Cube_cell.geometry}
            material={materials.Material}
            position={[0, 0, -0.92]}
          />
          <mesh
            name="Cube_cell001"
            geometry={nodes.Cube_cell001.geometry}
            material={materials.Material}
            position={[0, -0.89, -0.93]}
          />
          <mesh
            name="Cube_cell002"
            geometry={nodes.Cube_cell002.geometry}
            material={materials.Material}
            position={[0.03, 0.91, 0.9]}
          />
          <mesh
            name="Cube_cell003"
            geometry={nodes.Cube_cell003.geometry}
            material={materials.Material}
            position={[0.04, 1, -0.89]}
          />
          <mesh
            name="Cube_cell004"
            geometry={nodes.Cube_cell004.geometry}
            material={materials.Material}
            position={[-0.05, -0.95, -0.93]}
          />
          <mesh
            name="Cube_cell005"
            geometry={nodes.Cube_cell005.geometry}
            material={materials.Material}
            position={[-0.04, 0.91, 0.9]}
          />
          <mesh
            name="Cube_cell006"
            geometry={nodes.Cube_cell006.geometry}
            material={materials.Material}
            position={[0.01, -0.9, 0.92]}
          />
          <mesh
            name="Cube_cell007"
            geometry={nodes.Cube_cell007.geometry}
            material={materials.Material}
            position={[0, -0.98, -0.6]}
          />
          <mesh
            name="Cube_cell008"
            geometry={nodes.Cube_cell008.geometry}
            material={materials.Material}
            position={[0.01, -0.95, -0.14]}
          />
          <mesh
            name="Cube_cell009"
            geometry={nodes.Cube_cell009.geometry}
            material={materials.Material}
            position={[-0.03, -0.96, 0.33]}
          />
          <mesh
            name="Cube_cell010"
            geometry={nodes.Cube_cell010.geometry}
            material={materials.Material}
            position={[0, -0.96, 0.42]}
          />
          <mesh
            name="Cube_cell011"
            geometry={nodes.Cube_cell011.geometry}
            material={materials.Material}
            position={[-0.01, 0.89, -0.46]}
          />
          <mesh
            name="Cube_cell012"
            geometry={nodes.Cube_cell012.geometry}
            material={materials.Material}
            position={[-0.01, 0.89, -0.2]}
          />
          <mesh
            name="Cube_cell013"
            geometry={nodes.Cube_cell013.geometry}
            material={materials.Material}
            position={[0, 0.86, 0.32]}
          />
          <mesh
            name="Cube_cell014"
            geometry={nodes.Cube_cell014.geometry}
            material={materials.Material}
            position={[0, 0.79, 0.66]}
          />
          <mesh
            name="Cube_cell015"
            geometry={nodes.Cube_cell015.geometry}
            material={materials.Material}
            position={[0, 0.95, 0.7]}
          />
          <mesh
            name="Cube_cell016"
            geometry={nodes.Cube_cell016.geometry}
            material={materials.Material}
            position={[0, 0.93, 0.02]}
          />
          <mesh
            name="Cube_cell017"
            geometry={nodes.Cube_cell017.geometry}
            material={materials.Material}
            position={[-0.05, 0.97, -0.18]}
          />
          <mesh
            name="Cube_cell018"
            geometry={nodes.Cube_cell018.geometry}
            material={materials.Material}
            position={[0, 0.86, -0.71]}
          />
          <mesh
            name="Cube_cell019"
            geometry={nodes.Cube_cell019.geometry}
            material={materials.Material}
            position={[0, -0.9, 0.65]}
          />
          <mesh
            name="Cube_cell020"
            geometry={nodes.Cube_cell020.geometry}
            material={materials.Material}
            position={[0.01, -0.92, 0.18]}
          />
          <mesh
            name="Cube_cell021"
            geometry={nodes.Cube_cell021.geometry}
            material={materials.Material}
            position={[0, -0.9, -0.4]}
          />
          <mesh
            name="Cube_cell022"
            geometry={nodes.Cube_cell022.geometry}
            material={materials.Material}
            position={[0.01, -0.88, -0.76]}
          />
          <mesh
            name="Cube_cell023"
            geometry={nodes.Cube_cell023.geometry}
            material={materials.Material}
            position={[0, 0.73, -0.87]}
          />
          <mesh
            name="Cube_cell025"
            geometry={nodes.Cube_cell025.geometry}
            material={materials.Material}
            position={[0, -0.31, -0.9]}
          />
          <mesh
            name="Cube_cell026"
            geometry={nodes.Cube_cell026.geometry}
            material={materials.Material}
            position={[0, -0.66, -0.95]}
          />
          <mesh
            name="Cube_cell027"
            geometry={nodes.Cube_cell027.geometry}
            material={materials.Material}
            position={[0.01, -0.59, 0.89]}
          />
          <mesh
            name="Cube_cell029"
            geometry={nodes.Cube_cell029.geometry}
            material={materials.Material}
            position={[0, 0.22, 0.87]}
          />
          <mesh
            name="Cube_cell031"
            geometry={nodes.Cube_cell031.geometry}
            material={materials.Material}
            position={[0, 0.64, 0.9]}
          />
          <mesh
            name="Cube_cell032"
            geometry={nodes.Cube_cell032.geometry}
            material={materials.Material}
            position={[0, 0.22, 0.97]}
          />
          <mesh
            name="Cube_cell033"
            geometry={nodes.Cube_cell033.geometry}
            material={materials.Material}
            position={[0.01, -0.17, 0.87]}
          />
          <mesh
            name="Cube_cell035"
            geometry={nodes.Cube_cell035.geometry}
            material={materials.Material}
            position={[0, 0.47, -0.92]}
          />
          <mesh
            name="Cube_cell036"
            geometry={nodes.Cube_cell036.geometry}
            material={materials.Material}
            position={[0, 0.28, -0.87]}
          />
          <mesh
            name="Cube_cell037"
            geometry={nodes.Cube_cell037.geometry}
            material={materials.Material}
            position={[0.01, -0.02, -0.84]}
          />
          <mesh
            name="Cube_cell038"
            geometry={nodes.Cube_cell038.geometry}
            material={materials.Material}
            position={[0, -0.52, -0.79]}
          />
          <mesh
            name="Cube_cell039"
            geometry={nodes.Cube_cell039.geometry}
            material={materials.Material}
            position={[0.05, 0.73, -0.67]}
          />
          <mesh
            name="Cube_cell040"
            geometry={nodes.Cube_cell040.geometry}
            material={materials.Material}
            position={[0, 0.17, -0.72]}
          />
          <mesh
            name="Cube_cell041"
            geometry={nodes.Cube_cell041.geometry}
            material={materials.Material}
            position={[0, -0.17, -0.44]}
          />
          <mesh
            name="Cube_cell042"
            geometry={nodes.Cube_cell042.geometry}
            material={materials.Material}
            position={[0, -0.56, -0.47]}
          />
          <mesh
            name="Cube_cell043"
            geometry={nodes.Cube_cell043.geometry}
            material={materials.Material}
            position={[0.02, 0.65, -0.44]}
          />
          <mesh
            name="Cube_cell044"
            geometry={nodes.Cube_cell044.geometry}
            material={materials.Material}
            position={[0, 0.24, -0.23]}
          />
          <mesh
            name="Cube_cell045"
            geometry={nodes.Cube_cell045.geometry}
            material={materials.Material}
            position={[0, -0.2, -0.17]}
          />
          <mesh
            name="Cube_cell046"
            geometry={nodes.Cube_cell046.geometry}
            material={materials.Material}
            position={[0, -0.71, 0.05]}
          />
          <mesh
            name="Cube_cell047"
            geometry={nodes.Cube_cell047.geometry}
            material={materials.Material}
            position={[0, 0.58, 0.34]}
          />
          <mesh
            name="Cube_cell048"
            geometry={nodes.Cube_cell048.geometry}
            material={materials.Material}
            position={[0.04, 0.32, 0.3]}
          />
          <mesh
            name="Cube_cell049"
            geometry={nodes.Cube_cell049.geometry}
            material={materials.Material}
            position={[0, -0.38, 0.03]}
          />
          <mesh
            name="Cube_cell050"
            geometry={nodes.Cube_cell050.geometry}
            material={materials.Material}
            position={[0, -0.48, 0.29]}
          />
          <mesh
            name="Cube_cell051"
            geometry={nodes.Cube_cell051.geometry}
            material={materials.Material}
            position={[0, 0.42, 0.69]}
          />
          <mesh
            name="Cube_cell052"
            geometry={nodes.Cube_cell052.geometry}
            material={materials.Material}
            position={[0.01, 0, 0.49]}
          />
          <mesh
            name="Cube_cell053"
            geometry={nodes.Cube_cell053.geometry}
            material={materials.Material}
            position={[0, -0.44, 0.68]}
          />
          <mesh
            name="Cube_cell054"
            geometry={nodes.Cube_cell054.geometry}
            material={materials.Material}
            position={[-0.01, 0.57, 0.54]}
          />
          <mesh
            name="Cube_cell055"
            geometry={nodes.Cube_cell055.geometry}
            material={materials.Material}
            position={[0, 0.13, 0.61]}
          />
          <mesh
            name="Cube_cell056"
            geometry={nodes.Cube_cell056.geometry}
            material={materials.Material}
            position={[0, -0.24, 0.57]}
          />
          <mesh
            name="Cube_cell057"
            geometry={nodes.Cube_cell057.geometry}
            material={materials.Material}
            position={[0, -0.7, 0.59]}
          />
          <mesh
            name="Cube_cell058"
            geometry={nodes.Cube_cell058.geometry}
            material={materials.Material}
            position={[0, 0.61, 0.06]}
          />
          <mesh
            name="Cube_cell059"
            geometry={nodes.Cube_cell059.geometry}
            material={materials.Material}
            position={[-0.01, 0.21, 0.22]}
          />
          <mesh
            name="Cube_cell060"
            geometry={nodes.Cube_cell060.geometry}
            material={materials.Material}
            position={[0.01, -0.15, 0.2]}
          />
          <mesh
            name="Cube_cell061"
            geometry={nodes.Cube_cell061.geometry}
            material={materials.Material}
            position={[0, -0.78, 0.32]}
          />
          <mesh
            name="Cube_cell062"
            geometry={nodes.Cube_cell062.geometry}
            material={materials.Material}
            position={[-0.01, 0.62, -0.22]}
          />
          <mesh
            name="Cube_cell063"
            geometry={nodes.Cube_cell063.geometry}
            material={materials.Material}
            position={[-0.06, 0.02, -0.29]}
          />
          <mesh
            name="Cube_cell064"
            geometry={nodes.Cube_cell064.geometry}
            material={materials.Material}
            position={[-0.05, -0.38, -0.33]}
          />
          <mesh
            name="Cube_cell065"
            geometry={nodes.Cube_cell065.geometry}
            material={materials.Material}
            position={[-0.01, -0.61, -0.21]}
          />
          <mesh
            name="Cube_cell066"
            geometry={nodes.Cube_cell066.geometry}
            material={materials.Material}
            position={[0, 0.53, -0.65]}
          />
          <mesh
            name="Cube_cell067"
            geometry={nodes.Cube_cell067.geometry}
            material={materials.Material}
            position={[0.02, 0.16, -0.58]}
          />
          <mesh
            name="Cube_cell068"
            geometry={nodes.Cube_cell068.geometry}
            material={materials.Material}
            position={[0, -0.22, -0.67]}
          />
          <mesh
            name="Cube_cell069"
            geometry={nodes.Cube_cell069.geometry}
            material={materials.Material}
            position={[0, -0.76, -0.64]}
          />
          <mesh
            name="Cube_cell024"
            geometry={nodes.Cube_cell024.geometry}
            material={materials.Material}
            position={[0, 0.92, 1.08]}
          />
          <mesh
            name="Cube_cell030"
            geometry={nodes.Cube_cell030.geometry}
            material={materials.Material}
            position={[0, -0.89, 1.07]}
          />
          <mesh
            name="Cube_cell034"
            geometry={nodes.Cube_cell034.geometry}
            material={materials.Material}
            position={[0.03, 0.91, 2.9]}
          />
          <mesh
            name="Cube_cell070"
            geometry={nodes.Cube_cell070.geometry}
            material={materials.Material}
            position={[0.04, 1, 1.11]}
          />
          <mesh
            name="Cube_cell071"
            geometry={nodes.Cube_cell071.geometry}
            material={materials.Material}
            position={[-0.05, -0.95, 1.07]}
          />
          <mesh
            name="Cube_cell072"
            geometry={nodes.Cube_cell072.geometry}
            material={materials.Material}
            position={[-0.04, 0.91, 2.89]}
          />
          <mesh
            name="Cube_cell073"
            geometry={nodes.Cube_cell073.geometry}
            material={materials.Material}
            position={[0.01, -0.9, 2.92]}
          />
          <mesh
            name="Cube_cell074"
            geometry={nodes.Cube_cell074.geometry}
            material={materials.Material}
            position={[0, -0.98, 1.39]}
          />
          <mesh
            name="Cube_cell075"
            geometry={nodes.Cube_cell075.geometry}
            material={materials.Material}
            position={[0.01, -0.95, 1.85]}
          />
          <mesh
            name="Cube_cell076"
            geometry={nodes.Cube_cell076.geometry}
            material={materials.Material}
            position={[-0.03, -0.96, 2.33]}
          />
          <mesh
            name="Cube_cell077"
            geometry={nodes.Cube_cell077.geometry}
            material={materials.Material}
            position={[0, -0.96, 2.42]}
          />
          <mesh
            name="Cube_cell078"
            geometry={nodes.Cube_cell078.geometry}
            material={materials.Material}
            position={[-0.01, 0.89, 1.54]}
          />
          <mesh
            name="Cube_cell079"
            geometry={nodes.Cube_cell079.geometry}
            material={materials.Material}
            position={[-0.01, 0.89, 1.8]}
          />
          <mesh
            name="Cube_cell080"
            geometry={nodes.Cube_cell080.geometry}
            material={materials.Material}
            position={[0, 0.86, 2.32]}
          />
          <mesh
            name="Cube_cell081"
            geometry={nodes.Cube_cell081.geometry}
            material={materials.Material}
            position={[0, 0.79, 2.66]}
          />
          <mesh
            name="Cube_cell082"
            geometry={nodes.Cube_cell082.geometry}
            material={materials.Material}
            position={[0, 0.95, 2.7]}
          />
          <mesh
            name="Cube_cell083"
            geometry={nodes.Cube_cell083.geometry}
            material={materials.Material}
            position={[0, 0.93, 2.02]}
          />
          <mesh
            name="Cube_cell084"
            geometry={nodes.Cube_cell084.geometry}
            material={materials.Material}
            position={[-0.05, 0.97, 1.82]}
          />
          <mesh
            name="Cube_cell085"
            geometry={nodes.Cube_cell085.geometry}
            material={materials.Material}
            position={[0, 0.86, 1.29]}
          />
          <mesh
            name="Cube_cell086"
            geometry={nodes.Cube_cell086.geometry}
            material={materials.Material}
            position={[0, -0.9, 2.65]}
          />
          <mesh
            name="Cube_cell087"
            geometry={nodes.Cube_cell087.geometry}
            material={materials.Material}
            position={[0.01, -0.92, 2.18]}
          />
          <mesh
            name="Cube_cell088"
            geometry={nodes.Cube_cell088.geometry}
            material={materials.Material}
            position={[0, -0.9, 1.59]}
          />
          <mesh
            name="Cube_cell089"
            geometry={nodes.Cube_cell089.geometry}
            material={materials.Material}
            position={[0.01, -0.88, 1.24]}
          />
          <mesh
            name="Cube_cell090"
            geometry={nodes.Cube_cell090.geometry}
            material={materials.Material}
            position={[0, 0.73, 1.13]}
          />
          <mesh
            name="Cube_cell091"
            geometry={nodes.Cube_cell091.geometry}
            material={materials.Material}
            position={[0, -0.31, 1.1]}
          />
          <mesh
            name="Cube_cell092"
            geometry={nodes.Cube_cell092.geometry}
            material={materials.Material}
            position={[0, -0.66, 1.04]}
          />
          <mesh
            name="Cube_cell093"
            geometry={nodes.Cube_cell093.geometry}
            material={materials.Material}
            position={[0.01, -0.59, 2.89]}
          />
          <mesh
            name="Cube_cell095"
            geometry={nodes.Cube_cell095.geometry}
            material={materials.Material}
            position={[0, 0.22, 2.87]}
          />
          <mesh
            name="Cube_cell096"
            geometry={nodes.Cube_cell096.geometry}
            material={materials.Material}
            position={[0, 0.64, 2.9]}
          />
          <mesh
            name="Cube_cell097"
            geometry={nodes.Cube_cell097.geometry}
            material={materials.Material}
            position={[0, 0.22, 2.97]}
          />
          <mesh
            name="Cube_cell098"
            geometry={nodes.Cube_cell098.geometry}
            material={materials.Material}
            position={[0.01, -0.17, 2.87]}
          />
          <mesh
            name="Cube_cell099"
            geometry={nodes.Cube_cell099.geometry}
            material={materials.Material}
            position={[0, 0.47, 1.08]}
          />
          <mesh
            name="Cube_cell100"
            geometry={nodes.Cube_cell100.geometry}
            material={materials.Material}
            position={[0, 0.28, 1.13]}
          />
          <mesh
            name="Cube_cell101"
            geometry={nodes.Cube_cell101.geometry}
            material={materials.Material}
            position={[0.01, -0.02, 1.16]}
          />
          <mesh
            name="Cube_cell102"
            geometry={nodes.Cube_cell102.geometry}
            material={materials.Material}
            position={[0, -0.52, 1.21]}
          />
          <mesh
            name="Cube_cell103"
            geometry={nodes.Cube_cell103.geometry}
            material={materials.Material}
            position={[0.05, 0.73, 1.33]}
          />
          <mesh
            name="Cube_cell104"
            geometry={nodes.Cube_cell104.geometry}
            material={materials.Material}
            position={[0, 0.17, 1.27]}
          />
          <mesh
            name="Cube_cell105"
            geometry={nodes.Cube_cell105.geometry}
            material={materials.Material}
            position={[0, -0.17, 1.56]}
          />
          <mesh
            name="Cube_cell106"
            geometry={nodes.Cube_cell106.geometry}
            material={materials.Material}
            position={[0, -0.56, 1.53]}
          />
          <mesh
            name="Cube_cell107"
            geometry={nodes.Cube_cell107.geometry}
            material={materials.Material}
            position={[0.02, 0.65, 1.56]}
          />
          <mesh
            name="Cube_cell108"
            geometry={nodes.Cube_cell108.geometry}
            material={materials.Material}
            position={[0, 0.24, 1.77]}
          />
          <mesh
            name="Cube_cell109"
            geometry={nodes.Cube_cell109.geometry}
            material={materials.Material}
            position={[0, -0.2, 1.82]}
          />
          <mesh
            name="Cube_cell110"
            geometry={nodes.Cube_cell110.geometry}
            material={materials.Material}
            position={[0, -0.71, 2.04]}
          />
          <mesh
            name="Cube_cell111"
            geometry={nodes.Cube_cell111.geometry}
            material={materials.Material}
            position={[0, 0.58, 2.34]}
          />
          <mesh
            name="Cube_cell112"
            geometry={nodes.Cube_cell112.geometry}
            material={materials.Material}
            position={[0.04, 0.32, 2.3]}
          />
          <mesh
            name="Cube_cell113"
            geometry={nodes.Cube_cell113.geometry}
            material={materials.Material}
            position={[0, -0.38, 2.03]}
          />
          <mesh
            name="Cube_cell114"
            geometry={nodes.Cube_cell114.geometry}
            material={materials.Material}
            position={[0, -0.48, 2.29]}
          />
          <mesh
            name="Cube_cell115"
            geometry={nodes.Cube_cell115.geometry}
            material={materials.Material}
            position={[0, 0.42, 2.69]}
          />
          <mesh
            name="Cube_cell116"
            geometry={nodes.Cube_cell116.geometry}
            material={materials.Material}
            position={[0.01, 0, 2.49]}
          />
          <mesh
            name="Cube_cell117"
            geometry={nodes.Cube_cell117.geometry}
            material={materials.Material}
            position={[0, -0.44, 2.68]}
          />
          <mesh
            name="Cube_cell118"
            geometry={nodes.Cube_cell118.geometry}
            material={materials.Material}
            position={[-0.01, 0.57, 2.54]}
          />
          <mesh
            name="Cube_cell119"
            geometry={nodes.Cube_cell119.geometry}
            material={materials.Material}
            position={[0, 0.13, 2.61]}
          />
          <mesh
            name="Cube_cell120"
            geometry={nodes.Cube_cell120.geometry}
            material={materials.Material}
            position={[0, -0.24, 2.57]}
          />
          <mesh
            name="Cube_cell121"
            geometry={nodes.Cube_cell121.geometry}
            material={materials.Material}
            position={[0, -0.7, 2.58]}
          />
          <mesh
            name="Cube_cell122"
            geometry={nodes.Cube_cell122.geometry}
            material={materials.Material}
            position={[0, 0.61, 2.06]}
          />
          <mesh
            name="Cube_cell123"
            geometry={nodes.Cube_cell123.geometry}
            material={materials.Material}
            position={[-0.01, 0.21, 2.21]}
          />
          <mesh
            name="Cube_cell124"
            geometry={nodes.Cube_cell124.geometry}
            material={materials.Material}
            position={[0.01, -0.15, 2.2]}
          />
          <mesh
            name="Cube_cell125"
            geometry={nodes.Cube_cell125.geometry}
            material={materials.Material}
            position={[0, -0.78, 2.32]}
          />
          <mesh
            name="Cube_cell126"
            geometry={nodes.Cube_cell126.geometry}
            material={materials.Material}
            position={[-0.01, 0.62, 1.77]}
          />
          <mesh
            name="Cube_cell127"
            geometry={nodes.Cube_cell127.geometry}
            material={materials.Material}
            position={[-0.06, 0.02, 1.71]}
          />
          <mesh
            name="Cube_cell128"
            geometry={nodes.Cube_cell128.geometry}
            material={materials.Material}
            position={[-0.05, -0.38, 1.66]}
          />
          <mesh
            name="Cube_cell129"
            geometry={nodes.Cube_cell129.geometry}
            material={materials.Material}
            position={[-0.01, -0.61, 1.79]}
          />
          <mesh
            name="Cube_cell130"
            geometry={nodes.Cube_cell130.geometry}
            material={materials.Material}
            position={[0, 0.53, 1.35]}
          />
          <mesh
            name="Cube_cell131"
            geometry={nodes.Cube_cell131.geometry}
            material={materials.Material}
            position={[0.02, 0.16, 1.41]}
          />
          <mesh
            name="Cube_cell132"
            geometry={nodes.Cube_cell132.geometry}
            material={materials.Material}
            position={[0, -0.22, 1.33]}
          />
          <mesh
            name="Cube_cell133"
            geometry={nodes.Cube_cell133.geometry}
            material={materials.Material}
            position={[0, -0.76, 1.36]}
          />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/windows.glb");
